-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
-- Version: 2019.1
-- Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity sobel_accel is
generic (
    C_S_AXI_AXILITES_ADDR_WIDTH : INTEGER := 5;
    C_S_AXI_AXILITES_DATA_WIDTH : INTEGER := 32 );
port (
    ap_clk : IN STD_LOGIC;
    ap_rst_n : IN STD_LOGIC;
    in_stream_TDATA : IN STD_LOGIC_VECTOR (7 downto 0);
    in_stream_TVALID : IN STD_LOGIC;
    in_stream_TREADY : OUT STD_LOGIC;
    in_stream_TKEEP : IN STD_LOGIC_VECTOR (0 downto 0);
    in_stream_TSTRB : IN STD_LOGIC_VECTOR (0 downto 0);
    in_stream_TUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    in_stream_TLAST : IN STD_LOGIC_VECTOR (0 downto 0);
    in_stream_TID : IN STD_LOGIC_VECTOR (0 downto 0);
    in_stream_TDEST : IN STD_LOGIC_VECTOR (0 downto 0);
    out_stream_TDATA : OUT STD_LOGIC_VECTOR (7 downto 0);
    out_stream_TVALID : OUT STD_LOGIC;
    out_stream_TREADY : IN STD_LOGIC;
    out_stream_TKEEP : OUT STD_LOGIC_VECTOR (0 downto 0);
    out_stream_TSTRB : OUT STD_LOGIC_VECTOR (0 downto 0);
    out_stream_TUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    out_stream_TLAST : OUT STD_LOGIC_VECTOR (0 downto 0);
    out_stream_TID : OUT STD_LOGIC_VECTOR (0 downto 0);
    out_stream_TDEST : OUT STD_LOGIC_VECTOR (0 downto 0);
    s_axi_AXILiteS_AWVALID : IN STD_LOGIC;
    s_axi_AXILiteS_AWREADY : OUT STD_LOGIC;
    s_axi_AXILiteS_AWADDR : IN STD_LOGIC_VECTOR (C_S_AXI_AXILITES_ADDR_WIDTH-1 downto 0);
    s_axi_AXILiteS_WVALID : IN STD_LOGIC;
    s_axi_AXILiteS_WREADY : OUT STD_LOGIC;
    s_axi_AXILiteS_WDATA : IN STD_LOGIC_VECTOR (C_S_AXI_AXILITES_DATA_WIDTH-1 downto 0);
    s_axi_AXILiteS_WSTRB : IN STD_LOGIC_VECTOR (C_S_AXI_AXILITES_DATA_WIDTH/8-1 downto 0);
    s_axi_AXILiteS_ARVALID : IN STD_LOGIC;
    s_axi_AXILiteS_ARREADY : OUT STD_LOGIC;
    s_axi_AXILiteS_ARADDR : IN STD_LOGIC_VECTOR (C_S_AXI_AXILITES_ADDR_WIDTH-1 downto 0);
    s_axi_AXILiteS_RVALID : OUT STD_LOGIC;
    s_axi_AXILiteS_RREADY : IN STD_LOGIC;
    s_axi_AXILiteS_RDATA : OUT STD_LOGIC_VECTOR (C_S_AXI_AXILITES_DATA_WIDTH-1 downto 0);
    s_axi_AXILiteS_RRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
    s_axi_AXILiteS_BVALID : OUT STD_LOGIC;
    s_axi_AXILiteS_BREADY : IN STD_LOGIC;
    s_axi_AXILiteS_BRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
    interrupt : OUT STD_LOGIC );
end;


architecture behav of sobel_accel is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "sobel_accel,hls_ip_2019_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z010-clg400-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=8.510000,HLS_SYN_LAT=307206,HLS_SYN_TPT=none,HLS_SYN_MEM=2,HLS_SYN_DSP=4,HLS_SYN_FF=1035,HLS_SYN_LUT=1332,HLS_VERSION=2019_1}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (3 downto 0) := "0010";
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (3 downto 0) := "0100";
    constant ap_ST_fsm_state8 : STD_LOGIC_VECTOR (3 downto 0) := "1000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv2_2 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_const_lv2_3 : STD_LOGIC_VECTOR (1 downto 0) := "11";
    constant ap_const_lv2_1 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant C_S_AXI_DATA_WIDTH : INTEGER range 63 downto 0 := 20;
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv64_0 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv31_0 : STD_LOGIC_VECTOR (30 downto 0) := "0000000000000000000000000000000";
    constant ap_const_lv32_FFFFFFFF : STD_LOGIC_VECTOR (31 downto 0) := "11111111111111111111111111111111";
    constant ap_const_lv32_1E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011110";
    constant ap_const_lv30_0 : STD_LOGIC_VECTOR (29 downto 0) := "000000000000000000000000000000";
    constant ap_const_lv64_1 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000001";
    constant ap_const_lv31_1 : STD_LOGIC_VECTOR (30 downto 0) := "0000000000000000000000000000001";
    constant ap_const_lv32_A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001010";
    constant ap_const_lv11_0 : STD_LOGIC_VECTOR (10 downto 0) := "00000000000";
    constant ap_const_lv12_6D : STD_LOGIC_VECTOR (11 downto 0) := "000001101101";
    constant ap_const_lv8_FF : STD_LOGIC_VECTOR (7 downto 0) := "11111111";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";

    signal ap_rst_n_inv : STD_LOGIC;
    signal ap_start : STD_LOGIC;
    signal ap_done : STD_LOGIC;
    signal ap_idle : STD_LOGIC;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal ap_ready : STD_LOGIC;
    signal in_stream_V_data_V_0_data_out : STD_LOGIC_VECTOR (7 downto 0);
    signal in_stream_V_data_V_0_vld_in : STD_LOGIC;
    signal in_stream_V_data_V_0_vld_out : STD_LOGIC;
    signal in_stream_V_data_V_0_ack_in : STD_LOGIC;
    signal in_stream_V_data_V_0_ack_out : STD_LOGIC;
    signal in_stream_V_data_V_0_payload_A : STD_LOGIC_VECTOR (7 downto 0);
    signal in_stream_V_data_V_0_payload_B : STD_LOGIC_VECTOR (7 downto 0);
    signal in_stream_V_data_V_0_sel_rd : STD_LOGIC := '0';
    signal in_stream_V_data_V_0_sel_wr : STD_LOGIC := '0';
    signal in_stream_V_data_V_0_sel : STD_LOGIC;
    signal in_stream_V_data_V_0_load_A : STD_LOGIC;
    signal in_stream_V_data_V_0_load_B : STD_LOGIC;
    signal in_stream_V_data_V_0_state : STD_LOGIC_VECTOR (1 downto 0) := "00";
    signal in_stream_V_data_V_0_state_cmp_full : STD_LOGIC;
    signal in_stream_V_dest_V_0_vld_in : STD_LOGIC;
    signal in_stream_V_dest_V_0_ack_out : STD_LOGIC;
    signal in_stream_V_dest_V_0_state : STD_LOGIC_VECTOR (1 downto 0) := "00";
    signal out_stream_V_data_V_1_data_out : STD_LOGIC_VECTOR (7 downto 0);
    signal out_stream_V_data_V_1_vld_in : STD_LOGIC;
    signal out_stream_V_data_V_1_vld_out : STD_LOGIC;
    signal out_stream_V_data_V_1_ack_in : STD_LOGIC;
    signal out_stream_V_data_V_1_ack_out : STD_LOGIC;
    signal out_stream_V_data_V_1_payload_A : STD_LOGIC_VECTOR (7 downto 0);
    signal out_stream_V_data_V_1_payload_B : STD_LOGIC_VECTOR (7 downto 0);
    signal out_stream_V_data_V_1_sel_rd : STD_LOGIC := '0';
    signal out_stream_V_data_V_1_sel_wr : STD_LOGIC := '0';
    signal out_stream_V_data_V_1_sel : STD_LOGIC;
    signal out_stream_V_data_V_1_load_A : STD_LOGIC;
    signal out_stream_V_data_V_1_load_B : STD_LOGIC;
    signal out_stream_V_data_V_1_state : STD_LOGIC_VECTOR (1 downto 0) := "00";
    signal out_stream_V_data_V_1_state_cmp_full : STD_LOGIC;
    signal out_stream_V_keep_V_1_data_out : STD_LOGIC_VECTOR (0 downto 0);
    signal out_stream_V_keep_V_1_vld_in : STD_LOGIC;
    signal out_stream_V_keep_V_1_vld_out : STD_LOGIC;
    signal out_stream_V_keep_V_1_ack_out : STD_LOGIC;
    signal out_stream_V_keep_V_1_sel_rd : STD_LOGIC := '0';
    signal out_stream_V_keep_V_1_sel : STD_LOGIC;
    signal out_stream_V_keep_V_1_state : STD_LOGIC_VECTOR (1 downto 0) := "00";
    signal out_stream_V_strb_V_1_data_out : STD_LOGIC_VECTOR (0 downto 0);
    signal out_stream_V_strb_V_1_vld_in : STD_LOGIC;
    signal out_stream_V_strb_V_1_vld_out : STD_LOGIC;
    signal out_stream_V_strb_V_1_ack_out : STD_LOGIC;
    signal out_stream_V_strb_V_1_sel_rd : STD_LOGIC := '0';
    signal out_stream_V_strb_V_1_sel : STD_LOGIC;
    signal out_stream_V_strb_V_1_state : STD_LOGIC_VECTOR (1 downto 0) := "00";
    signal out_stream_V_user_V_1_data_out : STD_LOGIC_VECTOR (0 downto 0);
    signal out_stream_V_user_V_1_vld_in : STD_LOGIC;
    signal out_stream_V_user_V_1_vld_out : STD_LOGIC;
    signal out_stream_V_user_V_1_ack_out : STD_LOGIC;
    signal out_stream_V_user_V_1_sel_rd : STD_LOGIC := '0';
    signal out_stream_V_user_V_1_sel : STD_LOGIC;
    signal out_stream_V_user_V_1_state : STD_LOGIC_VECTOR (1 downto 0) := "00";
    signal out_stream_V_last_V_1_data_out : STD_LOGIC_VECTOR (0 downto 0);
    signal out_stream_V_last_V_1_vld_in : STD_LOGIC;
    signal out_stream_V_last_V_1_vld_out : STD_LOGIC;
    signal out_stream_V_last_V_1_ack_in : STD_LOGIC;
    signal out_stream_V_last_V_1_ack_out : STD_LOGIC;
    signal out_stream_V_last_V_1_payload_A : STD_LOGIC_VECTOR (0 downto 0);
    signal out_stream_V_last_V_1_payload_B : STD_LOGIC_VECTOR (0 downto 0);
    signal out_stream_V_last_V_1_sel_rd : STD_LOGIC := '0';
    signal out_stream_V_last_V_1_sel_wr : STD_LOGIC := '0';
    signal out_stream_V_last_V_1_sel : STD_LOGIC;
    signal out_stream_V_last_V_1_load_A : STD_LOGIC;
    signal out_stream_V_last_V_1_load_B : STD_LOGIC;
    signal out_stream_V_last_V_1_state : STD_LOGIC_VECTOR (1 downto 0) := "00";
    signal out_stream_V_last_V_1_state_cmp_full : STD_LOGIC;
    signal out_stream_V_id_V_1_data_out : STD_LOGIC_VECTOR (0 downto 0);
    signal out_stream_V_id_V_1_vld_in : STD_LOGIC;
    signal out_stream_V_id_V_1_vld_out : STD_LOGIC;
    signal out_stream_V_id_V_1_ack_out : STD_LOGIC;
    signal out_stream_V_id_V_1_sel_rd : STD_LOGIC := '0';
    signal out_stream_V_id_V_1_sel : STD_LOGIC;
    signal out_stream_V_id_V_1_state : STD_LOGIC_VECTOR (1 downto 0) := "00";
    signal out_stream_V_dest_V_1_data_out : STD_LOGIC_VECTOR (0 downto 0);
    signal out_stream_V_dest_V_1_vld_in : STD_LOGIC;
    signal out_stream_V_dest_V_1_vld_out : STD_LOGIC;
    signal out_stream_V_dest_V_1_ack_out : STD_LOGIC;
    signal out_stream_V_dest_V_1_sel_rd : STD_LOGIC := '0';
    signal out_stream_V_dest_V_1_sel : STD_LOGIC;
    signal out_stream_V_dest_V_1_state : STD_LOGIC_VECTOR (1 downto 0) := "00";
    signal width : STD_LOGIC_VECTOR (31 downto 0);
    signal height : STD_LOGIC_VECTOR (31 downto 0);
    signal line_buffer_V_0_address0 : STD_LOGIC_VECTOR (9 downto 0);
    signal line_buffer_V_0_ce0 : STD_LOGIC;
    signal line_buffer_V_0_q0 : STD_LOGIC_VECTOR (7 downto 0);
    signal line_buffer_V_0_ce1 : STD_LOGIC;
    signal line_buffer_V_0_we1 : STD_LOGIC;
    signal line_buffer_V_1_address0 : STD_LOGIC_VECTOR (9 downto 0);
    signal line_buffer_V_1_ce0 : STD_LOGIC;
    signal line_buffer_V_1_q0 : STD_LOGIC_VECTOR (7 downto 0);
    signal line_buffer_V_1_ce1 : STD_LOGIC;
    signal line_buffer_V_1_we1 : STD_LOGIC;
    signal in_stream_TDATA_blk_n : STD_LOGIC;
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC := '0';
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal icmp_ln20_fu_322_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal out_stream_TDATA_blk_n : STD_LOGIC;
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal icmp_ln20_reg_789 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln20_reg_789_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_reg_pp0_iter4 : STD_LOGIC := '0';
    signal icmp_ln20_reg_789_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal indvar_flatten_reg_233 : STD_LOGIC_VECTOR (63 downto 0);
    signal r_0_reg_244 : STD_LOGIC_VECTOR (30 downto 0);
    signal c_0_reg_255 : STD_LOGIC_VECTOR (30 downto 0);
    signal height_read_reg_750 : STD_LOGIC_VECTOR (31 downto 0);
    signal width_read_reg_756 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln83_fu_266_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln83_reg_763 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal add_ln83_1_fu_271_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln83_1_reg_769 : STD_LOGIC_VECTOR (31 downto 0);
    signal bound_fu_282_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal bound_reg_774 : STD_LOGIC_VECTOR (63 downto 0);
    signal icmp_ln48_fu_307_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln48_reg_779 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_state3_pp0_stage0_iter0 : BOOLEAN;
    signal ap_block_state4_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_state5_pp0_stage0_iter2 : BOOLEAN;
    signal ap_block_state6_pp0_stage0_iter3 : BOOLEAN;
    signal ap_block_state6_io : BOOLEAN;
    signal ap_block_state7_pp0_stage0_iter4 : BOOLEAN;
    signal ap_block_state7_io : BOOLEAN;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal icmp_ln48_reg_779_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln48_reg_779_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln24_fu_317_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln24_reg_784 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln24_reg_784_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln24_reg_784_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln20_reg_789_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln20_fu_327_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal icmp_ln48_1_fu_374_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln48_1_reg_798 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln48_1_reg_798_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln48_1_reg_798_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln20_3_fu_384_p3 : STD_LOGIC_VECTOR (30 downto 0);
    signal tmp_data_V_2_reg_808 : STD_LOGIC_VECTOR (7 downto 0);
    signal line_buffer_V_0_addr_reg_816 : STD_LOGIC_VECTOR (9 downto 0);
    signal line_buffer_V_1_addr_reg_822 : STD_LOGIC_VECTOR (9 downto 0);
    signal icmp_ln48_2_fu_412_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln48_2_reg_828 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln48_2_reg_828_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln48_2_reg_828_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_last_V_fu_423_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_last_V_reg_833 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_last_V_reg_833_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_last_V_reg_833_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal c_fu_429_p2 : STD_LOGIC_VECTOR (30 downto 0);
    signal window_2_1_V_load_reg_843 : STD_LOGIC_VECTOR (7 downto 0);
    signal window_0_2_V_reg_848 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal window_1_2_V_reg_853 : STD_LOGIC_VECTOR (7 downto 0);
    signal ret_V_fu_482_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal ret_V_reg_858 : STD_LOGIC_VECTOR (8 downto 0);
    signal sub_ln58_1_fu_520_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal sub_ln58_1_reg_863 : STD_LOGIC_VECTOR (10 downto 0);
    signal sub_ln67_1_fu_554_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal sub_ln67_1_reg_868 : STD_LOGIC_VECTOR (10 downto 0);
    signal mag_fu_676_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal mag_reg_873 : STD_LOGIC_VECTOR (11 downto 0);
    signal tmp_data_V_1_fu_703_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_condition_pp0_exit_iter1_state4 : STD_LOGIC;
    signal zext_ln39_fu_396_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal window_V_0_1_1_fu_114 : STD_LOGIC_VECTOR (7 downto 0);
    signal window_0_1_V_fu_118 : STD_LOGIC_VECTOR (7 downto 0);
    signal window_V_1_1_1_fu_122 : STD_LOGIC_VECTOR (7 downto 0);
    signal window_1_1_V_fu_126 : STD_LOGIC_VECTOR (7 downto 0);
    signal window_V_2_1_1_fu_130 : STD_LOGIC_VECTOR (7 downto 0);
    signal window_2_1_V_fu_134 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_block_pp0_stage0_01001 : BOOLEAN;
    signal bound_fu_282_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal bound_fu_282_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal zext_ln20_1_fu_288_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_fu_297_p4 : STD_LOGIC_VECTOR (29 downto 0);
    signal zext_ln24_fu_313_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln20_1_fu_333_p2 : STD_LOGIC_VECTOR (30 downto 0);
    signal zext_ln20_fu_339_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal icmp_ln83_fu_292_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln83_2_fu_351_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_2_fu_364_p4 : STD_LOGIC_VECTOR (29 downto 0);
    signal select_ln20_fu_343_p3 : STD_LOGIC_VECTOR (30 downto 0);
    signal tmp_5_fu_402_p4 : STD_LOGIC_VECTOR (29 downto 0);
    signal zext_ln20_2_fu_380_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln20_1_fu_356_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln83_1_fu_418_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal zext_ln215_fu_478_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal rhs_V_fu_474_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal shl_ln_fu_488_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal zext_ln58_4_fu_507_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal zext_ln58_fu_496_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal sub_ln58_fu_510_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal sext_ln58_1_fu_516_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal zext_ln58_2_fu_500_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal shl_ln67_1_fu_526_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal zext_ln58_3_fu_504_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal sub_ln67_fu_538_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal zext_ln67_fu_534_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal sext_ln67_fu_544_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal add_ln67_fu_548_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal shl_ln58_1_fu_577_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal sext_ln58_fu_574_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal zext_ln58_1_fu_584_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal add_ln58_fu_588_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal shl_ln1_fu_602_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal zext_ln67_2_fu_609_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal zext_ln67_1_fu_599_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal sub_ln67_2_fu_613_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal gx_fu_594_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal tmp_3_fu_624_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal sub_ln71_fu_632_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal gx_1_fu_638_p3 : STD_LOGIC_VECTOR (10 downto 0);
    signal gy_fu_618_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal tmp_4_fu_650_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal sub_ln71_1_fu_658_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal gy_1_fu_664_p3 : STD_LOGIC_VECTOR (10 downto 0);
    signal sext_ln71_1_fu_672_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal sext_ln71_fu_646_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal select_ln20_2_fu_682_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln74_fu_687_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln48_fu_692_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_data_V_fu_697_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state8 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state8 : signal is "none";
    signal ap_block_state8 : BOOLEAN;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_enable_pp0 : STD_LOGIC;
    signal bound_fu_282_p00 : STD_LOGIC_VECTOR (63 downto 0);
    signal bound_fu_282_p10 : STD_LOGIC_VECTOR (63 downto 0);

    component sobel_accel_line_bkb IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (9 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (7 downto 0);
        address1 : IN STD_LOGIC_VECTOR (9 downto 0);
        ce1 : IN STD_LOGIC;
        we1 : IN STD_LOGIC;
        d1 : IN STD_LOGIC_VECTOR (7 downto 0) );
    end component;


    component sobel_accel_AXILiteS_s_axi IS
    generic (
        C_S_AXI_ADDR_WIDTH : INTEGER;
        C_S_AXI_DATA_WIDTH : INTEGER );
    port (
        AWVALID : IN STD_LOGIC;
        AWREADY : OUT STD_LOGIC;
        AWADDR : IN STD_LOGIC_VECTOR (C_S_AXI_ADDR_WIDTH-1 downto 0);
        WVALID : IN STD_LOGIC;
        WREADY : OUT STD_LOGIC;
        WDATA : IN STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH-1 downto 0);
        WSTRB : IN STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH/8-1 downto 0);
        ARVALID : IN STD_LOGIC;
        ARREADY : OUT STD_LOGIC;
        ARADDR : IN STD_LOGIC_VECTOR (C_S_AXI_ADDR_WIDTH-1 downto 0);
        RVALID : OUT STD_LOGIC;
        RREADY : IN STD_LOGIC;
        RDATA : OUT STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH-1 downto 0);
        RRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
        BVALID : OUT STD_LOGIC;
        BREADY : IN STD_LOGIC;
        BRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
        ACLK : IN STD_LOGIC;
        ARESET : IN STD_LOGIC;
        ACLK_EN : IN STD_LOGIC;
        ap_start : OUT STD_LOGIC;
        interrupt : OUT STD_LOGIC;
        ap_ready : IN STD_LOGIC;
        ap_done : IN STD_LOGIC;
        ap_idle : IN STD_LOGIC;
        width : OUT STD_LOGIC_VECTOR (31 downto 0);
        height : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;



begin
    line_buffer_V_0_U : component sobel_accel_line_bkb
    generic map (
        DataWidth => 8,
        AddressRange => 640,
        AddressWidth => 10)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        address0 => line_buffer_V_0_address0,
        ce0 => line_buffer_V_0_ce0,
        q0 => line_buffer_V_0_q0,
        address1 => line_buffer_V_0_addr_reg_816,
        ce1 => line_buffer_V_0_ce1,
        we1 => line_buffer_V_0_we1,
        d1 => line_buffer_V_1_q0);

    line_buffer_V_1_U : component sobel_accel_line_bkb
    generic map (
        DataWidth => 8,
        AddressRange => 640,
        AddressWidth => 10)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        address0 => line_buffer_V_1_address0,
        ce0 => line_buffer_V_1_ce0,
        q0 => line_buffer_V_1_q0,
        address1 => line_buffer_V_1_addr_reg_822,
        ce1 => line_buffer_V_1_ce1,
        we1 => line_buffer_V_1_we1,
        d1 => tmp_data_V_2_reg_808);

    sobel_accel_AXILiteS_s_axi_U : component sobel_accel_AXILiteS_s_axi
    generic map (
        C_S_AXI_ADDR_WIDTH => C_S_AXI_AXILITES_ADDR_WIDTH,
        C_S_AXI_DATA_WIDTH => C_S_AXI_AXILITES_DATA_WIDTH)
    port map (
        AWVALID => s_axi_AXILiteS_AWVALID,
        AWREADY => s_axi_AXILiteS_AWREADY,
        AWADDR => s_axi_AXILiteS_AWADDR,
        WVALID => s_axi_AXILiteS_WVALID,
        WREADY => s_axi_AXILiteS_WREADY,
        WDATA => s_axi_AXILiteS_WDATA,
        WSTRB => s_axi_AXILiteS_WSTRB,
        ARVALID => s_axi_AXILiteS_ARVALID,
        ARREADY => s_axi_AXILiteS_ARREADY,
        ARADDR => s_axi_AXILiteS_ARADDR,
        RVALID => s_axi_AXILiteS_RVALID,
        RREADY => s_axi_AXILiteS_RREADY,
        RDATA => s_axi_AXILiteS_RDATA,
        RRESP => s_axi_AXILiteS_RRESP,
        BVALID => s_axi_AXILiteS_BVALID,
        BREADY => s_axi_AXILiteS_BREADY,
        BRESP => s_axi_AXILiteS_BRESP,
        ACLK => ap_clk,
        ARESET => ap_rst_n_inv,
        ACLK_EN => ap_const_logic_1,
        ap_start => ap_start,
        interrupt => interrupt,
        ap_ready => ap_ready,
        ap_done => ap_done,
        ap_idle => ap_idle,
        width => width,
        height => height);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter0_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_enable_reg_pp0_iter0 <= ap_const_logic_0;
            else
                if (((icmp_ln20_fu_322_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
                    ap_enable_reg_pp0_iter0 <= ap_const_logic_0;
                elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
                    ap_enable_reg_pp0_iter0 <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then
                    if ((ap_const_logic_1 = ap_condition_pp0_exit_iter1_state4)) then 
                        ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter0;
                    elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                        ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                    end if;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter4_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_enable_reg_pp0_iter4 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
                elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
                    ap_enable_reg_pp0_iter4 <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    in_stream_V_data_V_0_sel_rd_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                in_stream_V_data_V_0_sel_rd <= ap_const_logic_0;
            else
                if (((in_stream_V_data_V_0_ack_out = ap_const_logic_1) and (in_stream_V_data_V_0_vld_out = ap_const_logic_1))) then 
                                        in_stream_V_data_V_0_sel_rd <= not(in_stream_V_data_V_0_sel_rd);
                end if; 
            end if;
        end if;
    end process;


    in_stream_V_data_V_0_sel_wr_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                in_stream_V_data_V_0_sel_wr <= ap_const_logic_0;
            else
                if (((in_stream_V_data_V_0_ack_in = ap_const_logic_1) and (in_stream_V_data_V_0_vld_in = ap_const_logic_1))) then 
                                        in_stream_V_data_V_0_sel_wr <= not(in_stream_V_data_V_0_sel_wr);
                end if; 
            end if;
        end if;
    end process;


    in_stream_V_data_V_0_state_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                in_stream_V_data_V_0_state <= ap_const_lv2_0;
            else
                if ((((in_stream_V_data_V_0_state = ap_const_lv2_2) and (in_stream_V_data_V_0_vld_in = ap_const_logic_0)) or ((in_stream_V_data_V_0_state = ap_const_lv2_3) and (in_stream_V_data_V_0_vld_in = ap_const_logic_0) and (in_stream_V_data_V_0_ack_out = ap_const_logic_1)))) then 
                    in_stream_V_data_V_0_state <= ap_const_lv2_2;
                elsif ((((in_stream_V_data_V_0_state = ap_const_lv2_1) and (in_stream_V_data_V_0_ack_out = ap_const_logic_0)) or ((in_stream_V_data_V_0_state = ap_const_lv2_3) and (in_stream_V_data_V_0_ack_out = ap_const_logic_0) and (in_stream_V_data_V_0_vld_in = ap_const_logic_1)))) then 
                    in_stream_V_data_V_0_state <= ap_const_lv2_1;
                elsif (((not(((in_stream_V_data_V_0_vld_in = ap_const_logic_0) and (in_stream_V_data_V_0_ack_out = ap_const_logic_1))) and not(((in_stream_V_data_V_0_ack_out = ap_const_logic_0) and (in_stream_V_data_V_0_vld_in = ap_const_logic_1))) and (in_stream_V_data_V_0_state = ap_const_lv2_3)) or ((in_stream_V_data_V_0_state = ap_const_lv2_1) and (in_stream_V_data_V_0_ack_out = ap_const_logic_1)) or ((in_stream_V_data_V_0_state = ap_const_lv2_2) and (in_stream_V_data_V_0_vld_in = ap_const_logic_1)))) then 
                    in_stream_V_data_V_0_state <= ap_const_lv2_3;
                else 
                    in_stream_V_data_V_0_state <= ap_const_lv2_2;
                end if; 
            end if;
        end if;
    end process;


    in_stream_V_dest_V_0_state_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                in_stream_V_dest_V_0_state <= ap_const_lv2_0;
            else
                if ((((in_stream_V_dest_V_0_state = ap_const_lv2_2) and (in_stream_V_dest_V_0_vld_in = ap_const_logic_0)) or ((in_stream_V_dest_V_0_state = ap_const_lv2_3) and (in_stream_V_dest_V_0_vld_in = ap_const_logic_0) and (in_stream_V_dest_V_0_ack_out = ap_const_logic_1)))) then 
                    in_stream_V_dest_V_0_state <= ap_const_lv2_2;
                elsif ((((in_stream_V_dest_V_0_state = ap_const_lv2_1) and (in_stream_V_dest_V_0_ack_out = ap_const_logic_0)) or ((in_stream_V_dest_V_0_state = ap_const_lv2_3) and (in_stream_V_dest_V_0_ack_out = ap_const_logic_0) and (in_stream_V_dest_V_0_vld_in = ap_const_logic_1)))) then 
                    in_stream_V_dest_V_0_state <= ap_const_lv2_1;
                elsif (((not(((in_stream_V_dest_V_0_vld_in = ap_const_logic_0) and (in_stream_V_dest_V_0_ack_out = ap_const_logic_1))) and not(((in_stream_V_dest_V_0_ack_out = ap_const_logic_0) and (in_stream_V_dest_V_0_vld_in = ap_const_logic_1))) and (in_stream_V_dest_V_0_state = ap_const_lv2_3)) or ((in_stream_V_dest_V_0_state = ap_const_lv2_1) and (in_stream_V_dest_V_0_ack_out = ap_const_logic_1)) or ((in_stream_V_dest_V_0_state = ap_const_lv2_2) and (in_stream_V_dest_V_0_vld_in = ap_const_logic_1)))) then 
                    in_stream_V_dest_V_0_state <= ap_const_lv2_3;
                else 
                    in_stream_V_dest_V_0_state <= ap_const_lv2_2;
                end if; 
            end if;
        end if;
    end process;


    out_stream_V_data_V_1_sel_rd_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                out_stream_V_data_V_1_sel_rd <= ap_const_logic_0;
            else
                if (((out_stream_V_data_V_1_ack_out = ap_const_logic_1) and (out_stream_V_data_V_1_vld_out = ap_const_logic_1))) then 
                                        out_stream_V_data_V_1_sel_rd <= not(out_stream_V_data_V_1_sel_rd);
                end if; 
            end if;
        end if;
    end process;


    out_stream_V_data_V_1_sel_wr_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                out_stream_V_data_V_1_sel_wr <= ap_const_logic_0;
            else
                if (((out_stream_V_data_V_1_ack_in = ap_const_logic_1) and (out_stream_V_data_V_1_vld_in = ap_const_logic_1))) then 
                                        out_stream_V_data_V_1_sel_wr <= not(out_stream_V_data_V_1_sel_wr);
                end if; 
            end if;
        end if;
    end process;


    out_stream_V_data_V_1_state_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                out_stream_V_data_V_1_state <= ap_const_lv2_0;
            else
                if ((((out_stream_V_data_V_1_state = ap_const_lv2_2) and (out_stream_V_data_V_1_vld_in = ap_const_logic_0)) or ((out_stream_V_data_V_1_state = ap_const_lv2_3) and (out_stream_V_data_V_1_vld_in = ap_const_logic_0) and (out_stream_V_data_V_1_ack_out = ap_const_logic_1)))) then 
                    out_stream_V_data_V_1_state <= ap_const_lv2_2;
                elsif ((((out_stream_V_data_V_1_state = ap_const_lv2_1) and (out_stream_TREADY = ap_const_logic_0)) or ((out_stream_V_data_V_1_state = ap_const_lv2_3) and (out_stream_TREADY = ap_const_logic_0) and (out_stream_V_data_V_1_vld_in = ap_const_logic_1)))) then 
                    out_stream_V_data_V_1_state <= ap_const_lv2_1;
                elsif (((not(((out_stream_V_data_V_1_vld_in = ap_const_logic_0) and (out_stream_V_data_V_1_ack_out = ap_const_logic_1))) and not(((out_stream_TREADY = ap_const_logic_0) and (out_stream_V_data_V_1_vld_in = ap_const_logic_1))) and (out_stream_V_data_V_1_state = ap_const_lv2_3)) or ((out_stream_V_data_V_1_state = ap_const_lv2_1) and (out_stream_V_data_V_1_ack_out = ap_const_logic_1)) or ((out_stream_V_data_V_1_state = ap_const_lv2_2) and (out_stream_V_data_V_1_vld_in = ap_const_logic_1)))) then 
                    out_stream_V_data_V_1_state <= ap_const_lv2_3;
                else 
                    out_stream_V_data_V_1_state <= ap_const_lv2_2;
                end if; 
            end if;
        end if;
    end process;


    out_stream_V_dest_V_1_sel_rd_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                out_stream_V_dest_V_1_sel_rd <= ap_const_logic_0;
            else
                if (((out_stream_V_dest_V_1_ack_out = ap_const_logic_1) and (out_stream_V_dest_V_1_vld_out = ap_const_logic_1))) then 
                                        out_stream_V_dest_V_1_sel_rd <= not(out_stream_V_dest_V_1_sel_rd);
                end if; 
            end if;
        end if;
    end process;


    out_stream_V_dest_V_1_state_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                out_stream_V_dest_V_1_state <= ap_const_lv2_0;
            else
                if ((((out_stream_V_dest_V_1_state = ap_const_lv2_2) and (out_stream_V_dest_V_1_vld_in = ap_const_logic_0)) or ((out_stream_V_dest_V_1_state = ap_const_lv2_3) and (out_stream_V_dest_V_1_vld_in = ap_const_logic_0) and (out_stream_V_dest_V_1_ack_out = ap_const_logic_1)))) then 
                    out_stream_V_dest_V_1_state <= ap_const_lv2_2;
                elsif ((((out_stream_V_dest_V_1_state = ap_const_lv2_1) and (out_stream_TREADY = ap_const_logic_0)) or ((out_stream_V_dest_V_1_state = ap_const_lv2_3) and (out_stream_TREADY = ap_const_logic_0) and (out_stream_V_dest_V_1_vld_in = ap_const_logic_1)))) then 
                    out_stream_V_dest_V_1_state <= ap_const_lv2_1;
                elsif (((not(((out_stream_V_dest_V_1_vld_in = ap_const_logic_0) and (out_stream_V_dest_V_1_ack_out = ap_const_logic_1))) and not(((out_stream_TREADY = ap_const_logic_0) and (out_stream_V_dest_V_1_vld_in = ap_const_logic_1))) and (out_stream_V_dest_V_1_state = ap_const_lv2_3)) or ((out_stream_V_dest_V_1_state = ap_const_lv2_1) and (out_stream_V_dest_V_1_ack_out = ap_const_logic_1)) or ((out_stream_V_dest_V_1_state = ap_const_lv2_2) and (out_stream_V_dest_V_1_vld_in = ap_const_logic_1)))) then 
                    out_stream_V_dest_V_1_state <= ap_const_lv2_3;
                else 
                    out_stream_V_dest_V_1_state <= ap_const_lv2_2;
                end if; 
            end if;
        end if;
    end process;


    out_stream_V_id_V_1_sel_rd_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                out_stream_V_id_V_1_sel_rd <= ap_const_logic_0;
            else
                if (((out_stream_V_id_V_1_ack_out = ap_const_logic_1) and (out_stream_V_id_V_1_vld_out = ap_const_logic_1))) then 
                                        out_stream_V_id_V_1_sel_rd <= not(out_stream_V_id_V_1_sel_rd);
                end if; 
            end if;
        end if;
    end process;


    out_stream_V_id_V_1_state_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                out_stream_V_id_V_1_state <= ap_const_lv2_0;
            else
                if ((((out_stream_V_id_V_1_state = ap_const_lv2_2) and (out_stream_V_id_V_1_vld_in = ap_const_logic_0)) or ((out_stream_V_id_V_1_state = ap_const_lv2_3) and (out_stream_V_id_V_1_vld_in = ap_const_logic_0) and (out_stream_V_id_V_1_ack_out = ap_const_logic_1)))) then 
                    out_stream_V_id_V_1_state <= ap_const_lv2_2;
                elsif ((((out_stream_V_id_V_1_state = ap_const_lv2_1) and (out_stream_TREADY = ap_const_logic_0)) or ((out_stream_V_id_V_1_state = ap_const_lv2_3) and (out_stream_TREADY = ap_const_logic_0) and (out_stream_V_id_V_1_vld_in = ap_const_logic_1)))) then 
                    out_stream_V_id_V_1_state <= ap_const_lv2_1;
                elsif (((not(((out_stream_V_id_V_1_vld_in = ap_const_logic_0) and (out_stream_V_id_V_1_ack_out = ap_const_logic_1))) and not(((out_stream_TREADY = ap_const_logic_0) and (out_stream_V_id_V_1_vld_in = ap_const_logic_1))) and (out_stream_V_id_V_1_state = ap_const_lv2_3)) or ((out_stream_V_id_V_1_state = ap_const_lv2_1) and (out_stream_V_id_V_1_ack_out = ap_const_logic_1)) or ((out_stream_V_id_V_1_state = ap_const_lv2_2) and (out_stream_V_id_V_1_vld_in = ap_const_logic_1)))) then 
                    out_stream_V_id_V_1_state <= ap_const_lv2_3;
                else 
                    out_stream_V_id_V_1_state <= ap_const_lv2_2;
                end if; 
            end if;
        end if;
    end process;


    out_stream_V_keep_V_1_sel_rd_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                out_stream_V_keep_V_1_sel_rd <= ap_const_logic_0;
            else
                if (((out_stream_V_keep_V_1_ack_out = ap_const_logic_1) and (out_stream_V_keep_V_1_vld_out = ap_const_logic_1))) then 
                                        out_stream_V_keep_V_1_sel_rd <= not(out_stream_V_keep_V_1_sel_rd);
                end if; 
            end if;
        end if;
    end process;


    out_stream_V_keep_V_1_state_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                out_stream_V_keep_V_1_state <= ap_const_lv2_0;
            else
                if ((((out_stream_V_keep_V_1_state = ap_const_lv2_2) and (out_stream_V_keep_V_1_vld_in = ap_const_logic_0)) or ((out_stream_V_keep_V_1_state = ap_const_lv2_3) and (out_stream_V_keep_V_1_vld_in = ap_const_logic_0) and (out_stream_V_keep_V_1_ack_out = ap_const_logic_1)))) then 
                    out_stream_V_keep_V_1_state <= ap_const_lv2_2;
                elsif ((((out_stream_V_keep_V_1_state = ap_const_lv2_1) and (out_stream_TREADY = ap_const_logic_0)) or ((out_stream_V_keep_V_1_state = ap_const_lv2_3) and (out_stream_TREADY = ap_const_logic_0) and (out_stream_V_keep_V_1_vld_in = ap_const_logic_1)))) then 
                    out_stream_V_keep_V_1_state <= ap_const_lv2_1;
                elsif (((not(((out_stream_V_keep_V_1_vld_in = ap_const_logic_0) and (out_stream_V_keep_V_1_ack_out = ap_const_logic_1))) and not(((out_stream_TREADY = ap_const_logic_0) and (out_stream_V_keep_V_1_vld_in = ap_const_logic_1))) and (out_stream_V_keep_V_1_state = ap_const_lv2_3)) or ((out_stream_V_keep_V_1_state = ap_const_lv2_1) and (out_stream_V_keep_V_1_ack_out = ap_const_logic_1)) or ((out_stream_V_keep_V_1_state = ap_const_lv2_2) and (out_stream_V_keep_V_1_vld_in = ap_const_logic_1)))) then 
                    out_stream_V_keep_V_1_state <= ap_const_lv2_3;
                else 
                    out_stream_V_keep_V_1_state <= ap_const_lv2_2;
                end if; 
            end if;
        end if;
    end process;


    out_stream_V_last_V_1_sel_rd_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                out_stream_V_last_V_1_sel_rd <= ap_const_logic_0;
            else
                if (((out_stream_V_last_V_1_ack_out = ap_const_logic_1) and (out_stream_V_last_V_1_vld_out = ap_const_logic_1))) then 
                                        out_stream_V_last_V_1_sel_rd <= not(out_stream_V_last_V_1_sel_rd);
                end if; 
            end if;
        end if;
    end process;


    out_stream_V_last_V_1_sel_wr_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                out_stream_V_last_V_1_sel_wr <= ap_const_logic_0;
            else
                if (((out_stream_V_last_V_1_ack_in = ap_const_logic_1) and (out_stream_V_last_V_1_vld_in = ap_const_logic_1))) then 
                                        out_stream_V_last_V_1_sel_wr <= not(out_stream_V_last_V_1_sel_wr);
                end if; 
            end if;
        end if;
    end process;


    out_stream_V_last_V_1_state_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                out_stream_V_last_V_1_state <= ap_const_lv2_0;
            else
                if ((((out_stream_V_last_V_1_state = ap_const_lv2_2) and (out_stream_V_last_V_1_vld_in = ap_const_logic_0)) or ((out_stream_V_last_V_1_state = ap_const_lv2_3) and (out_stream_V_last_V_1_vld_in = ap_const_logic_0) and (out_stream_V_last_V_1_ack_out = ap_const_logic_1)))) then 
                    out_stream_V_last_V_1_state <= ap_const_lv2_2;
                elsif ((((out_stream_V_last_V_1_state = ap_const_lv2_1) and (out_stream_TREADY = ap_const_logic_0)) or ((out_stream_V_last_V_1_state = ap_const_lv2_3) and (out_stream_TREADY = ap_const_logic_0) and (out_stream_V_last_V_1_vld_in = ap_const_logic_1)))) then 
                    out_stream_V_last_V_1_state <= ap_const_lv2_1;
                elsif (((not(((out_stream_V_last_V_1_vld_in = ap_const_logic_0) and (out_stream_V_last_V_1_ack_out = ap_const_logic_1))) and not(((out_stream_TREADY = ap_const_logic_0) and (out_stream_V_last_V_1_vld_in = ap_const_logic_1))) and (out_stream_V_last_V_1_state = ap_const_lv2_3)) or ((out_stream_V_last_V_1_state = ap_const_lv2_1) and (out_stream_V_last_V_1_ack_out = ap_const_logic_1)) or ((out_stream_V_last_V_1_state = ap_const_lv2_2) and (out_stream_V_last_V_1_vld_in = ap_const_logic_1)))) then 
                    out_stream_V_last_V_1_state <= ap_const_lv2_3;
                else 
                    out_stream_V_last_V_1_state <= ap_const_lv2_2;
                end if; 
            end if;
        end if;
    end process;


    out_stream_V_strb_V_1_sel_rd_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                out_stream_V_strb_V_1_sel_rd <= ap_const_logic_0;
            else
                if (((out_stream_V_strb_V_1_ack_out = ap_const_logic_1) and (out_stream_V_strb_V_1_vld_out = ap_const_logic_1))) then 
                                        out_stream_V_strb_V_1_sel_rd <= not(out_stream_V_strb_V_1_sel_rd);
                end if; 
            end if;
        end if;
    end process;


    out_stream_V_strb_V_1_state_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                out_stream_V_strb_V_1_state <= ap_const_lv2_0;
            else
                if ((((out_stream_V_strb_V_1_state = ap_const_lv2_2) and (out_stream_V_strb_V_1_vld_in = ap_const_logic_0)) or ((out_stream_V_strb_V_1_state = ap_const_lv2_3) and (out_stream_V_strb_V_1_vld_in = ap_const_logic_0) and (out_stream_V_strb_V_1_ack_out = ap_const_logic_1)))) then 
                    out_stream_V_strb_V_1_state <= ap_const_lv2_2;
                elsif ((((out_stream_V_strb_V_1_state = ap_const_lv2_1) and (out_stream_TREADY = ap_const_logic_0)) or ((out_stream_V_strb_V_1_state = ap_const_lv2_3) and (out_stream_TREADY = ap_const_logic_0) and (out_stream_V_strb_V_1_vld_in = ap_const_logic_1)))) then 
                    out_stream_V_strb_V_1_state <= ap_const_lv2_1;
                elsif (((not(((out_stream_V_strb_V_1_vld_in = ap_const_logic_0) and (out_stream_V_strb_V_1_ack_out = ap_const_logic_1))) and not(((out_stream_TREADY = ap_const_logic_0) and (out_stream_V_strb_V_1_vld_in = ap_const_logic_1))) and (out_stream_V_strb_V_1_state = ap_const_lv2_3)) or ((out_stream_V_strb_V_1_state = ap_const_lv2_1) and (out_stream_V_strb_V_1_ack_out = ap_const_logic_1)) or ((out_stream_V_strb_V_1_state = ap_const_lv2_2) and (out_stream_V_strb_V_1_vld_in = ap_const_logic_1)))) then 
                    out_stream_V_strb_V_1_state <= ap_const_lv2_3;
                else 
                    out_stream_V_strb_V_1_state <= ap_const_lv2_2;
                end if; 
            end if;
        end if;
    end process;


    out_stream_V_user_V_1_sel_rd_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                out_stream_V_user_V_1_sel_rd <= ap_const_logic_0;
            else
                if (((out_stream_V_user_V_1_ack_out = ap_const_logic_1) and (out_stream_V_user_V_1_vld_out = ap_const_logic_1))) then 
                                        out_stream_V_user_V_1_sel_rd <= not(out_stream_V_user_V_1_sel_rd);
                end if; 
            end if;
        end if;
    end process;


    out_stream_V_user_V_1_state_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                out_stream_V_user_V_1_state <= ap_const_lv2_0;
            else
                if ((((out_stream_V_user_V_1_state = ap_const_lv2_2) and (out_stream_V_user_V_1_vld_in = ap_const_logic_0)) or ((out_stream_V_user_V_1_state = ap_const_lv2_3) and (out_stream_V_user_V_1_vld_in = ap_const_logic_0) and (out_stream_V_user_V_1_ack_out = ap_const_logic_1)))) then 
                    out_stream_V_user_V_1_state <= ap_const_lv2_2;
                elsif ((((out_stream_V_user_V_1_state = ap_const_lv2_1) and (out_stream_TREADY = ap_const_logic_0)) or ((out_stream_V_user_V_1_state = ap_const_lv2_3) and (out_stream_TREADY = ap_const_logic_0) and (out_stream_V_user_V_1_vld_in = ap_const_logic_1)))) then 
                    out_stream_V_user_V_1_state <= ap_const_lv2_1;
                elsif (((not(((out_stream_V_user_V_1_vld_in = ap_const_logic_0) and (out_stream_V_user_V_1_ack_out = ap_const_logic_1))) and not(((out_stream_TREADY = ap_const_logic_0) and (out_stream_V_user_V_1_vld_in = ap_const_logic_1))) and (out_stream_V_user_V_1_state = ap_const_lv2_3)) or ((out_stream_V_user_V_1_state = ap_const_lv2_1) and (out_stream_V_user_V_1_ack_out = ap_const_logic_1)) or ((out_stream_V_user_V_1_state = ap_const_lv2_2) and (out_stream_V_user_V_1_vld_in = ap_const_logic_1)))) then 
                    out_stream_V_user_V_1_state <= ap_const_lv2_3;
                else 
                    out_stream_V_user_V_1_state <= ap_const_lv2_2;
                end if; 
            end if;
        end if;
    end process;


    c_0_reg_255_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln20_fu_322_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                c_0_reg_255 <= c_fu_429_p2;
            elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
                c_0_reg_255 <= ap_const_lv31_0;
            end if; 
        end if;
    end process;

    indvar_flatten_reg_233_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln20_fu_322_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                indvar_flatten_reg_233 <= add_ln20_fu_327_p2;
            elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
                indvar_flatten_reg_233 <= ap_const_lv64_0;
            end if; 
        end if;
    end process;

    r_0_reg_244_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln20_fu_322_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                r_0_reg_244 <= select_ln20_3_fu_384_p3;
            elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
                r_0_reg_244 <= ap_const_lv31_0;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state2)) then
                add_ln83_1_reg_769 <= add_ln83_1_fu_271_p2;
                add_ln83_reg_763 <= add_ln83_fu_266_p2;
                bound_reg_774 <= bound_fu_282_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then
                height_read_reg_750 <= height;
                width_read_reg_756 <= width;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                icmp_ln20_reg_789 <= icmp_ln20_fu_322_p2;
                icmp_ln20_reg_789_pp0_iter1_reg <= icmp_ln20_reg_789;
                icmp_ln24_reg_784 <= icmp_ln24_fu_317_p2;
                icmp_ln24_reg_784_pp0_iter1_reg <= icmp_ln24_reg_784;
                icmp_ln48_1_reg_798_pp0_iter1_reg <= icmp_ln48_1_reg_798;
                icmp_ln48_2_reg_828_pp0_iter1_reg <= icmp_ln48_2_reg_828;
                icmp_ln48_reg_779 <= icmp_ln48_fu_307_p2;
                icmp_ln48_reg_779_pp0_iter1_reg <= icmp_ln48_reg_779;
                tmp_last_V_reg_833_pp0_iter1_reg <= tmp_last_V_reg_833;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                icmp_ln20_reg_789_pp0_iter2_reg <= icmp_ln20_reg_789_pp0_iter1_reg;
                icmp_ln20_reg_789_pp0_iter3_reg <= icmp_ln20_reg_789_pp0_iter2_reg;
                icmp_ln24_reg_784_pp0_iter2_reg <= icmp_ln24_reg_784_pp0_iter1_reg;
                icmp_ln48_1_reg_798_pp0_iter2_reg <= icmp_ln48_1_reg_798_pp0_iter1_reg;
                icmp_ln48_2_reg_828_pp0_iter2_reg <= icmp_ln48_2_reg_828_pp0_iter1_reg;
                icmp_ln48_reg_779_pp0_iter2_reg <= icmp_ln48_reg_779_pp0_iter1_reg;
                tmp_last_V_reg_833_pp0_iter2_reg <= tmp_last_V_reg_833_pp0_iter1_reg;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln20_fu_322_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                icmp_ln48_1_reg_798 <= icmp_ln48_1_fu_374_p2;
                icmp_ln48_2_reg_828 <= icmp_ln48_2_fu_412_p2;
                line_buffer_V_0_addr_reg_816 <= zext_ln39_fu_396_p1(10 - 1 downto 0);
                line_buffer_V_1_addr_reg_822 <= zext_ln39_fu_396_p1(10 - 1 downto 0);
                tmp_data_V_2_reg_808 <= in_stream_V_data_V_0_data_out;
                tmp_last_V_reg_833 <= tmp_last_V_fu_423_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((in_stream_V_data_V_0_load_A = ap_const_logic_1)) then
                in_stream_V_data_V_0_payload_A <= in_stream_TDATA;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((in_stream_V_data_V_0_load_B = ap_const_logic_1)) then
                in_stream_V_data_V_0_payload_B <= in_stream_TDATA;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln20_reg_789_pp0_iter1_reg = ap_const_lv1_0))) then
                mag_reg_873 <= mag_fu_676_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((out_stream_V_data_V_1_load_A = ap_const_logic_1)) then
                out_stream_V_data_V_1_payload_A <= tmp_data_V_1_fu_703_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((out_stream_V_data_V_1_load_B = ap_const_logic_1)) then
                out_stream_V_data_V_1_payload_B <= tmp_data_V_1_fu_703_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((out_stream_V_last_V_1_load_A = ap_const_logic_1)) then
                out_stream_V_last_V_1_payload_A <= tmp_last_V_reg_833_pp0_iter2_reg;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((out_stream_V_last_V_1_load_B = ap_const_logic_1)) then
                out_stream_V_last_V_1_payload_B <= tmp_last_V_reg_833_pp0_iter2_reg;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln20_reg_789 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                ret_V_reg_858 <= ret_V_fu_482_p2;
                sub_ln58_1_reg_863 <= sub_ln58_1_fu_520_p2;
                sub_ln67_1_reg_868 <= sub_ln67_1_fu_554_p2;
                window_2_1_V_load_reg_843 <= window_2_1_V_fu_134;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln20_reg_789 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1))) then
                window_0_1_V_fu_118 <= line_buffer_V_0_q0;
                window_0_2_V_reg_848 <= line_buffer_V_0_q0;
                window_1_1_V_fu_126 <= line_buffer_V_1_q0;
                window_1_2_V_reg_853 <= line_buffer_V_1_q0;
                window_2_1_V_fu_134 <= tmp_data_V_2_reg_808;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1))) then
                window_V_0_1_1_fu_114 <= window_0_1_V_fu_118;
                window_V_1_1_1_fu_122 <= window_1_1_V_fu_126;
                window_V_2_1_1_fu_130 <= window_2_1_V_fu_134;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, out_stream_TREADY, out_stream_V_data_V_1_state, out_stream_V_keep_V_1_state, out_stream_V_strb_V_1_state, out_stream_V_user_V_1_state, out_stream_V_last_V_1_state, out_stream_V_id_V_1_state, out_stream_V_dest_V_1_state, ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_subdone, ap_enable_reg_pp0_iter2, ap_CS_fsm_state8)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when ap_ST_fsm_pp0_stage0 => 
                if ((not(((ap_enable_reg_pp0_iter0 = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) and not(((ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                elsif ((((ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) or ((ap_enable_reg_pp0_iter0 = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone)))) then
                    ap_NS_fsm <= ap_ST_fsm_state8;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                end if;
            when ap_ST_fsm_state8 => 
                if ((not(((out_stream_V_dest_V_1_state = ap_const_lv2_1) or (out_stream_V_id_V_1_state = ap_const_lv2_1) or (out_stream_V_last_V_1_state = ap_const_lv2_1) or (out_stream_V_user_V_1_state = ap_const_lv2_1) or (out_stream_V_strb_V_1_state = ap_const_lv2_1) or (out_stream_V_keep_V_1_state = ap_const_lv2_1) or (out_stream_V_data_V_1_state = ap_const_lv2_1) or ((out_stream_V_dest_V_1_state = ap_const_lv2_3) and (out_stream_TREADY = ap_const_logic_0)) or ((out_stream_V_id_V_1_state = ap_const_lv2_3) and (out_stream_TREADY = ap_const_logic_0)) or ((out_stream_V_last_V_1_state = ap_const_lv2_3) and (out_stream_TREADY = ap_const_logic_0)) or ((out_stream_V_user_V_1_state = ap_const_lv2_3) and (out_stream_TREADY = ap_const_logic_0)) or ((out_stream_V_strb_V_1_state = ap_const_lv2_3) and (out_stream_TREADY = ap_const_logic_0)) or ((out_stream_V_keep_V_1_state = ap_const_lv2_3) and (out_stream_TREADY = ap_const_logic_0)) or ((out_stream_V_data_V_1_state = ap_const_lv2_3) and (out_stream_TREADY = ap_const_logic_0)))) and (ap_const_logic_1 = ap_CS_fsm_state8))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state8;
                end if;
            when others =>  
                ap_NS_fsm <= "XXXX";
        end case;
    end process;
    add_ln20_1_fu_333_p2 <= std_logic_vector(unsigned(ap_const_lv31_1) + unsigned(r_0_reg_244));
    add_ln20_fu_327_p2 <= std_logic_vector(unsigned(indvar_flatten_reg_233) + unsigned(ap_const_lv64_1));
    add_ln58_fu_588_p2 <= std_logic_vector(signed(sext_ln58_fu_574_p1) + signed(zext_ln58_1_fu_584_p1));
    add_ln67_fu_548_p2 <= std_logic_vector(unsigned(zext_ln67_fu_534_p1) + unsigned(sext_ln67_fu_544_p1));
    add_ln83_1_fu_271_p2 <= std_logic_vector(unsigned(width_read_reg_756) + unsigned(ap_const_lv32_FFFFFFFF));
    add_ln83_fu_266_p2 <= std_logic_vector(unsigned(height_read_reg_750) + unsigned(ap_const_lv32_FFFFFFFF));
    and_ln48_fu_692_p2 <= (select_ln20_2_fu_682_p3 and icmp_ln48_2_reg_828_pp0_iter2_reg);
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(2);
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state8 <= ap_CS_fsm(3);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_01001_assign_proc : process(in_stream_V_data_V_0_vld_out, ap_enable_reg_pp0_iter0, icmp_ln20_fu_322_p2)
    begin
                ap_block_pp0_stage0_01001 <= ((icmp_ln20_fu_322_p2 = ap_const_lv1_0) and (in_stream_V_data_V_0_vld_out = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1));
    end process;


    ap_block_pp0_stage0_11001_assign_proc : process(in_stream_V_data_V_0_vld_out, ap_enable_reg_pp0_iter0, icmp_ln20_fu_322_p2, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4, ap_block_state6_io, ap_block_state7_io)
    begin
                ap_block_pp0_stage0_11001 <= (((ap_const_boolean_1 = ap_block_state7_io) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1)) or ((ap_const_boolean_1 = ap_block_state6_io) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1)) or ((icmp_ln20_fu_322_p2 = ap_const_lv1_0) and (in_stream_V_data_V_0_vld_out = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1)));
    end process;


    ap_block_pp0_stage0_subdone_assign_proc : process(in_stream_V_data_V_0_vld_out, ap_enable_reg_pp0_iter0, icmp_ln20_fu_322_p2, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4, ap_block_state6_io, ap_block_state7_io)
    begin
                ap_block_pp0_stage0_subdone <= (((ap_const_boolean_1 = ap_block_state7_io) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1)) or ((ap_const_boolean_1 = ap_block_state6_io) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1)) or ((icmp_ln20_fu_322_p2 = ap_const_lv1_0) and (in_stream_V_data_V_0_vld_out = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1)));
    end process;


    ap_block_state3_pp0_stage0_iter0_assign_proc : process(in_stream_V_data_V_0_vld_out, icmp_ln20_fu_322_p2)
    begin
                ap_block_state3_pp0_stage0_iter0 <= ((icmp_ln20_fu_322_p2 = ap_const_lv1_0) and (in_stream_V_data_V_0_vld_out = ap_const_logic_0));
    end process;

        ap_block_state4_pp0_stage0_iter1 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state5_pp0_stage0_iter2 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_state6_io_assign_proc : process(out_stream_V_data_V_1_ack_in, icmp_ln20_reg_789_pp0_iter2_reg)
    begin
                ap_block_state6_io <= ((icmp_ln20_reg_789_pp0_iter2_reg = ap_const_lv1_0) and (out_stream_V_data_V_1_ack_in = ap_const_logic_0));
    end process;

        ap_block_state6_pp0_stage0_iter3 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_state7_io_assign_proc : process(out_stream_V_data_V_1_ack_in, icmp_ln20_reg_789_pp0_iter3_reg)
    begin
                ap_block_state7_io <= ((icmp_ln20_reg_789_pp0_iter3_reg = ap_const_lv1_0) and (out_stream_V_data_V_1_ack_in = ap_const_logic_0));
    end process;

        ap_block_state7_pp0_stage0_iter4 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_state8_assign_proc : process(out_stream_TREADY, out_stream_V_data_V_1_state, out_stream_V_keep_V_1_state, out_stream_V_strb_V_1_state, out_stream_V_user_V_1_state, out_stream_V_last_V_1_state, out_stream_V_id_V_1_state, out_stream_V_dest_V_1_state)
    begin
                ap_block_state8 <= ((out_stream_V_dest_V_1_state = ap_const_lv2_1) or (out_stream_V_id_V_1_state = ap_const_lv2_1) or (out_stream_V_last_V_1_state = ap_const_lv2_1) or (out_stream_V_user_V_1_state = ap_const_lv2_1) or (out_stream_V_strb_V_1_state = ap_const_lv2_1) or (out_stream_V_keep_V_1_state = ap_const_lv2_1) or (out_stream_V_data_V_1_state = ap_const_lv2_1) or ((out_stream_V_dest_V_1_state = ap_const_lv2_3) and (out_stream_TREADY = ap_const_logic_0)) or ((out_stream_V_id_V_1_state = ap_const_lv2_3) and (out_stream_TREADY = ap_const_logic_0)) or ((out_stream_V_last_V_1_state = ap_const_lv2_3) and (out_stream_TREADY = ap_const_logic_0)) or ((out_stream_V_user_V_1_state = ap_const_lv2_3) and (out_stream_TREADY = ap_const_logic_0)) or ((out_stream_V_strb_V_1_state = ap_const_lv2_3) and (out_stream_TREADY = ap_const_logic_0)) or ((out_stream_V_keep_V_1_state = ap_const_lv2_3) and (out_stream_TREADY = ap_const_logic_0)) or ((out_stream_V_data_V_1_state = ap_const_lv2_3) and (out_stream_TREADY = ap_const_logic_0)));
    end process;


    ap_condition_pp0_exit_iter1_state4_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1)
    begin
        if (((ap_enable_reg_pp0_iter0 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1))) then 
            ap_condition_pp0_exit_iter1_state4 <= ap_const_logic_1;
        else 
            ap_condition_pp0_exit_iter1_state4 <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_assign_proc : process(out_stream_TREADY, out_stream_V_data_V_1_state, out_stream_V_keep_V_1_state, out_stream_V_strb_V_1_state, out_stream_V_user_V_1_state, out_stream_V_last_V_1_state, out_stream_V_id_V_1_state, out_stream_V_dest_V_1_state, ap_CS_fsm_state8)
    begin
        if ((not(((out_stream_V_dest_V_1_state = ap_const_lv2_1) or (out_stream_V_id_V_1_state = ap_const_lv2_1) or (out_stream_V_last_V_1_state = ap_const_lv2_1) or (out_stream_V_user_V_1_state = ap_const_lv2_1) or (out_stream_V_strb_V_1_state = ap_const_lv2_1) or (out_stream_V_keep_V_1_state = ap_const_lv2_1) or (out_stream_V_data_V_1_state = ap_const_lv2_1) or ((out_stream_V_dest_V_1_state = ap_const_lv2_3) and (out_stream_TREADY = ap_const_logic_0)) or ((out_stream_V_id_V_1_state = ap_const_lv2_3) and (out_stream_TREADY = ap_const_logic_0)) or ((out_stream_V_last_V_1_state = ap_const_lv2_3) and (out_stream_TREADY = ap_const_logic_0)) or ((out_stream_V_user_V_1_state = ap_const_lv2_3) and (out_stream_TREADY = ap_const_logic_0)) or ((out_stream_V_strb_V_1_state = ap_const_lv2_3) and (out_stream_TREADY = ap_const_logic_0)) or ((out_stream_V_keep_V_1_state = ap_const_lv2_3) and (out_stream_TREADY = ap_const_logic_0)) or ((out_stream_V_data_V_1_state = ap_const_lv2_3) and (out_stream_TREADY = ap_const_logic_0)))) and (ap_const_logic_1 = ap_CS_fsm_state8))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);

    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2)
    begin
        if (((ap_enable_reg_pp0_iter4 = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(out_stream_TREADY, out_stream_V_data_V_1_state, out_stream_V_keep_V_1_state, out_stream_V_strb_V_1_state, out_stream_V_user_V_1_state, out_stream_V_last_V_1_state, out_stream_V_id_V_1_state, out_stream_V_dest_V_1_state, ap_CS_fsm_state8)
    begin
        if ((not(((out_stream_V_dest_V_1_state = ap_const_lv2_1) or (out_stream_V_id_V_1_state = ap_const_lv2_1) or (out_stream_V_last_V_1_state = ap_const_lv2_1) or (out_stream_V_user_V_1_state = ap_const_lv2_1) or (out_stream_V_strb_V_1_state = ap_const_lv2_1) or (out_stream_V_keep_V_1_state = ap_const_lv2_1) or (out_stream_V_data_V_1_state = ap_const_lv2_1) or ((out_stream_V_dest_V_1_state = ap_const_lv2_3) and (out_stream_TREADY = ap_const_logic_0)) or ((out_stream_V_id_V_1_state = ap_const_lv2_3) and (out_stream_TREADY = ap_const_logic_0)) or ((out_stream_V_last_V_1_state = ap_const_lv2_3) and (out_stream_TREADY = ap_const_logic_0)) or ((out_stream_V_user_V_1_state = ap_const_lv2_3) and (out_stream_TREADY = ap_const_logic_0)) or ((out_stream_V_strb_V_1_state = ap_const_lv2_3) and (out_stream_TREADY = ap_const_logic_0)) or ((out_stream_V_keep_V_1_state = ap_const_lv2_3) and (out_stream_TREADY = ap_const_logic_0)) or ((out_stream_V_data_V_1_state = ap_const_lv2_3) and (out_stream_TREADY = ap_const_logic_0)))) and (ap_const_logic_1 = ap_CS_fsm_state8))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    ap_rst_n_inv_assign_proc : process(ap_rst_n)
    begin
                ap_rst_n_inv <= not(ap_rst_n);
    end process;

    bound_fu_282_p0 <= bound_fu_282_p00(32 - 1 downto 0);
    bound_fu_282_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(width_read_reg_756),64));
    bound_fu_282_p1 <= bound_fu_282_p10(32 - 1 downto 0);
    bound_fu_282_p10 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(height_read_reg_750),64));
    bound_fu_282_p2 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(bound_fu_282_p0) * unsigned(bound_fu_282_p1), 64));
    c_fu_429_p2 <= std_logic_vector(unsigned(ap_const_lv31_1) + unsigned(select_ln20_fu_343_p3));
    gx_1_fu_638_p3 <= 
        sub_ln71_fu_632_p2 when (tmp_3_fu_624_p3(0) = '1') else 
        gx_fu_594_p2;
    gx_fu_594_p2 <= std_logic_vector(unsigned(sub_ln58_1_reg_863) + unsigned(add_ln58_fu_588_p2));
    gy_1_fu_664_p3 <= 
        sub_ln71_1_fu_658_p2 when (tmp_4_fu_650_p3(0) = '1') else 
        gy_fu_618_p2;
    gy_fu_618_p2 <= std_logic_vector(unsigned(zext_ln67_1_fu_599_p1) + unsigned(sub_ln67_2_fu_613_p2));
    icmp_ln20_fu_322_p2 <= "1" when (indvar_flatten_reg_233 = bound_reg_774) else "0";
    icmp_ln24_fu_317_p2 <= "1" when (signed(zext_ln24_fu_313_p1) < signed(width_read_reg_756)) else "0";
    icmp_ln48_1_fu_374_p2 <= "0" when (tmp_2_fu_364_p4 = ap_const_lv30_0) else "1";
    icmp_ln48_2_fu_412_p2 <= "0" when (tmp_5_fu_402_p4 = ap_const_lv30_0) else "1";
    icmp_ln48_fu_307_p2 <= "0" when (tmp_fu_297_p4 = ap_const_lv30_0) else "1";
    icmp_ln74_fu_687_p2 <= "1" when (signed(mag_reg_873) > signed(ap_const_lv12_6D)) else "0";
    icmp_ln83_1_fu_418_p2 <= "1" when (zext_ln20_2_fu_380_p1 = add_ln83_1_reg_769) else "0";
    icmp_ln83_2_fu_351_p2 <= "1" when (zext_ln20_fu_339_p1 = add_ln83_reg_763) else "0";
    icmp_ln83_fu_292_p2 <= "1" when (zext_ln20_1_fu_288_p1 = add_ln83_reg_763) else "0";

    in_stream_TDATA_blk_n_assign_proc : process(in_stream_V_data_V_0_state, ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0, icmp_ln20_fu_322_p2)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (icmp_ln20_fu_322_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            in_stream_TDATA_blk_n <= in_stream_V_data_V_0_state(0);
        else 
            in_stream_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    in_stream_TREADY <= in_stream_V_dest_V_0_state(1);
    in_stream_V_data_V_0_ack_in <= in_stream_V_data_V_0_state(1);

    in_stream_V_data_V_0_ack_out_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, icmp_ln20_fu_322_p2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln20_fu_322_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            in_stream_V_data_V_0_ack_out <= ap_const_logic_1;
        else 
            in_stream_V_data_V_0_ack_out <= ap_const_logic_0;
        end if; 
    end process;


    in_stream_V_data_V_0_data_out_assign_proc : process(in_stream_V_data_V_0_payload_A, in_stream_V_data_V_0_payload_B, in_stream_V_data_V_0_sel)
    begin
        if ((in_stream_V_data_V_0_sel = ap_const_logic_1)) then 
            in_stream_V_data_V_0_data_out <= in_stream_V_data_V_0_payload_B;
        else 
            in_stream_V_data_V_0_data_out <= in_stream_V_data_V_0_payload_A;
        end if; 
    end process;

    in_stream_V_data_V_0_load_A <= (in_stream_V_data_V_0_state_cmp_full and not(in_stream_V_data_V_0_sel_wr));
    in_stream_V_data_V_0_load_B <= (in_stream_V_data_V_0_state_cmp_full and in_stream_V_data_V_0_sel_wr);
    in_stream_V_data_V_0_sel <= in_stream_V_data_V_0_sel_rd;
    in_stream_V_data_V_0_state_cmp_full <= '0' when (in_stream_V_data_V_0_state = ap_const_lv2_1) else '1';
    in_stream_V_data_V_0_vld_in <= in_stream_TVALID;
    in_stream_V_data_V_0_vld_out <= in_stream_V_data_V_0_state(0);

    in_stream_V_dest_V_0_ack_out_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, icmp_ln20_fu_322_p2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln20_fu_322_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            in_stream_V_dest_V_0_ack_out <= ap_const_logic_1;
        else 
            in_stream_V_dest_V_0_ack_out <= ap_const_logic_0;
        end if; 
    end process;

    in_stream_V_dest_V_0_vld_in <= in_stream_TVALID;
    line_buffer_V_0_address0 <= zext_ln39_fu_396_p1(10 - 1 downto 0);

    line_buffer_V_0_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            line_buffer_V_0_ce0 <= ap_const_logic_1;
        else 
            line_buffer_V_0_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    line_buffer_V_0_ce1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, ap_enable_reg_pp0_iter1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1))) then 
            line_buffer_V_0_ce1 <= ap_const_logic_1;
        else 
            line_buffer_V_0_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    line_buffer_V_0_we1_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln20_reg_789, ap_block_pp0_stage0_11001, ap_enable_reg_pp0_iter1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln20_reg_789 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1))) then 
            line_buffer_V_0_we1 <= ap_const_logic_1;
        else 
            line_buffer_V_0_we1 <= ap_const_logic_0;
        end if; 
    end process;

    line_buffer_V_1_address0 <= zext_ln39_fu_396_p1(10 - 1 downto 0);

    line_buffer_V_1_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            line_buffer_V_1_ce0 <= ap_const_logic_1;
        else 
            line_buffer_V_1_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    line_buffer_V_1_ce1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, ap_enable_reg_pp0_iter1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1))) then 
            line_buffer_V_1_ce1 <= ap_const_logic_1;
        else 
            line_buffer_V_1_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    line_buffer_V_1_we1_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln20_reg_789, ap_block_pp0_stage0_11001, ap_enable_reg_pp0_iter1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln20_reg_789 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1))) then 
            line_buffer_V_1_we1 <= ap_const_logic_1;
        else 
            line_buffer_V_1_we1 <= ap_const_logic_0;
        end if; 
    end process;

    mag_fu_676_p2 <= std_logic_vector(signed(sext_ln71_1_fu_672_p1) + signed(sext_ln71_fu_646_p1));
    out_stream_TDATA <= out_stream_V_data_V_1_data_out;

    out_stream_TDATA_blk_n_assign_proc : process(out_stream_V_data_V_1_state, ap_block_pp0_stage0, ap_enable_reg_pp0_iter3, icmp_ln20_reg_789_pp0_iter2_reg, ap_enable_reg_pp0_iter4, icmp_ln20_reg_789_pp0_iter3_reg)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage0) and (icmp_ln20_reg_789_pp0_iter3_reg = ap_const_lv1_0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1)) or ((ap_const_boolean_0 = ap_block_pp0_stage0) and (icmp_ln20_reg_789_pp0_iter2_reg = ap_const_lv1_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1)))) then 
            out_stream_TDATA_blk_n <= out_stream_V_data_V_1_state(1);
        else 
            out_stream_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    out_stream_TDEST <= out_stream_V_dest_V_1_data_out;
    out_stream_TID <= out_stream_V_id_V_1_data_out;
    out_stream_TKEEP <= out_stream_V_keep_V_1_data_out;
    out_stream_TLAST <= out_stream_V_last_V_1_data_out;
    out_stream_TSTRB <= out_stream_V_strb_V_1_data_out;
    out_stream_TUSER <= out_stream_V_user_V_1_data_out;
    out_stream_TVALID <= out_stream_V_dest_V_1_state(0);
    out_stream_V_data_V_1_ack_in <= out_stream_V_data_V_1_state(1);
    out_stream_V_data_V_1_ack_out <= out_stream_TREADY;

    out_stream_V_data_V_1_data_out_assign_proc : process(out_stream_V_data_V_1_payload_A, out_stream_V_data_V_1_payload_B, out_stream_V_data_V_1_sel)
    begin
        if ((out_stream_V_data_V_1_sel = ap_const_logic_1)) then 
            out_stream_V_data_V_1_data_out <= out_stream_V_data_V_1_payload_B;
        else 
            out_stream_V_data_V_1_data_out <= out_stream_V_data_V_1_payload_A;
        end if; 
    end process;

    out_stream_V_data_V_1_load_A <= (out_stream_V_data_V_1_state_cmp_full and not(out_stream_V_data_V_1_sel_wr));
    out_stream_V_data_V_1_load_B <= (out_stream_V_data_V_1_state_cmp_full and out_stream_V_data_V_1_sel_wr);
    out_stream_V_data_V_1_sel <= out_stream_V_data_V_1_sel_rd;
    out_stream_V_data_V_1_state_cmp_full <= '0' when (out_stream_V_data_V_1_state = ap_const_lv2_1) else '1';

    out_stream_V_data_V_1_vld_in_assign_proc : process(ap_enable_reg_pp0_iter3, icmp_ln20_reg_789_pp0_iter2_reg, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln20_reg_789_pp0_iter2_reg = ap_const_lv1_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1))) then 
            out_stream_V_data_V_1_vld_in <= ap_const_logic_1;
        else 
            out_stream_V_data_V_1_vld_in <= ap_const_logic_0;
        end if; 
    end process;

    out_stream_V_data_V_1_vld_out <= out_stream_V_data_V_1_state(0);
    out_stream_V_dest_V_1_ack_out <= out_stream_TREADY;
    out_stream_V_dest_V_1_data_out <= ap_const_lv1_0;
    out_stream_V_dest_V_1_sel <= out_stream_V_dest_V_1_sel_rd;

    out_stream_V_dest_V_1_vld_in_assign_proc : process(ap_enable_reg_pp0_iter3, icmp_ln20_reg_789_pp0_iter2_reg, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln20_reg_789_pp0_iter2_reg = ap_const_lv1_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1))) then 
            out_stream_V_dest_V_1_vld_in <= ap_const_logic_1;
        else 
            out_stream_V_dest_V_1_vld_in <= ap_const_logic_0;
        end if; 
    end process;

    out_stream_V_dest_V_1_vld_out <= out_stream_V_dest_V_1_state(0);
    out_stream_V_id_V_1_ack_out <= out_stream_TREADY;
    out_stream_V_id_V_1_data_out <= ap_const_lv1_0;
    out_stream_V_id_V_1_sel <= out_stream_V_id_V_1_sel_rd;

    out_stream_V_id_V_1_vld_in_assign_proc : process(ap_enable_reg_pp0_iter3, icmp_ln20_reg_789_pp0_iter2_reg, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln20_reg_789_pp0_iter2_reg = ap_const_lv1_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1))) then 
            out_stream_V_id_V_1_vld_in <= ap_const_logic_1;
        else 
            out_stream_V_id_V_1_vld_in <= ap_const_logic_0;
        end if; 
    end process;

    out_stream_V_id_V_1_vld_out <= out_stream_V_id_V_1_state(0);
    out_stream_V_keep_V_1_ack_out <= out_stream_TREADY;
    out_stream_V_keep_V_1_data_out <= ap_const_lv1_1;
    out_stream_V_keep_V_1_sel <= out_stream_V_keep_V_1_sel_rd;

    out_stream_V_keep_V_1_vld_in_assign_proc : process(ap_enable_reg_pp0_iter3, icmp_ln20_reg_789_pp0_iter2_reg, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln20_reg_789_pp0_iter2_reg = ap_const_lv1_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1))) then 
            out_stream_V_keep_V_1_vld_in <= ap_const_logic_1;
        else 
            out_stream_V_keep_V_1_vld_in <= ap_const_logic_0;
        end if; 
    end process;

    out_stream_V_keep_V_1_vld_out <= out_stream_V_keep_V_1_state(0);
    out_stream_V_last_V_1_ack_in <= out_stream_V_last_V_1_state(1);
    out_stream_V_last_V_1_ack_out <= out_stream_TREADY;

    out_stream_V_last_V_1_data_out_assign_proc : process(out_stream_V_last_V_1_payload_A, out_stream_V_last_V_1_payload_B, out_stream_V_last_V_1_sel)
    begin
        if ((out_stream_V_last_V_1_sel = ap_const_logic_1)) then 
            out_stream_V_last_V_1_data_out <= out_stream_V_last_V_1_payload_B;
        else 
            out_stream_V_last_V_1_data_out <= out_stream_V_last_V_1_payload_A;
        end if; 
    end process;

    out_stream_V_last_V_1_load_A <= (out_stream_V_last_V_1_state_cmp_full and not(out_stream_V_last_V_1_sel_wr));
    out_stream_V_last_V_1_load_B <= (out_stream_V_last_V_1_state_cmp_full and out_stream_V_last_V_1_sel_wr);
    out_stream_V_last_V_1_sel <= out_stream_V_last_V_1_sel_rd;
    out_stream_V_last_V_1_state_cmp_full <= '0' when (out_stream_V_last_V_1_state = ap_const_lv2_1) else '1';

    out_stream_V_last_V_1_vld_in_assign_proc : process(ap_enable_reg_pp0_iter3, icmp_ln20_reg_789_pp0_iter2_reg, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln20_reg_789_pp0_iter2_reg = ap_const_lv1_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1))) then 
            out_stream_V_last_V_1_vld_in <= ap_const_logic_1;
        else 
            out_stream_V_last_V_1_vld_in <= ap_const_logic_0;
        end if; 
    end process;

    out_stream_V_last_V_1_vld_out <= out_stream_V_last_V_1_state(0);
    out_stream_V_strb_V_1_ack_out <= out_stream_TREADY;
    out_stream_V_strb_V_1_data_out <= ap_const_lv1_1;
    out_stream_V_strb_V_1_sel <= out_stream_V_strb_V_1_sel_rd;

    out_stream_V_strb_V_1_vld_in_assign_proc : process(ap_enable_reg_pp0_iter3, icmp_ln20_reg_789_pp0_iter2_reg, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln20_reg_789_pp0_iter2_reg = ap_const_lv1_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1))) then 
            out_stream_V_strb_V_1_vld_in <= ap_const_logic_1;
        else 
            out_stream_V_strb_V_1_vld_in <= ap_const_logic_0;
        end if; 
    end process;

    out_stream_V_strb_V_1_vld_out <= out_stream_V_strb_V_1_state(0);
    out_stream_V_user_V_1_ack_out <= out_stream_TREADY;
    out_stream_V_user_V_1_data_out <= ap_const_lv1_0;
    out_stream_V_user_V_1_sel <= out_stream_V_user_V_1_sel_rd;

    out_stream_V_user_V_1_vld_in_assign_proc : process(ap_enable_reg_pp0_iter3, icmp_ln20_reg_789_pp0_iter2_reg, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln20_reg_789_pp0_iter2_reg = ap_const_lv1_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1))) then 
            out_stream_V_user_V_1_vld_in <= ap_const_logic_1;
        else 
            out_stream_V_user_V_1_vld_in <= ap_const_logic_0;
        end if; 
    end process;

    out_stream_V_user_V_1_vld_out <= out_stream_V_user_V_1_state(0);
    ret_V_fu_482_p2 <= std_logic_vector(unsigned(zext_ln215_fu_478_p1) - unsigned(rhs_V_fu_474_p1));
    rhs_V_fu_474_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(window_V_0_1_1_fu_114),9));
    select_ln20_1_fu_356_p3 <= 
        icmp_ln83_fu_292_p2 when (icmp_ln24_fu_317_p2(0) = '1') else 
        icmp_ln83_2_fu_351_p2;
    select_ln20_2_fu_682_p3 <= 
        icmp_ln48_reg_779_pp0_iter2_reg when (icmp_ln24_reg_784_pp0_iter2_reg(0) = '1') else 
        icmp_ln48_1_reg_798_pp0_iter2_reg;
    select_ln20_3_fu_384_p3 <= 
        r_0_reg_244 when (icmp_ln24_fu_317_p2(0) = '1') else 
        add_ln20_1_fu_333_p2;
    select_ln20_fu_343_p3 <= 
        c_0_reg_255 when (icmp_ln24_fu_317_p2(0) = '1') else 
        ap_const_lv31_0;
        sext_ln58_1_fu_516_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sub_ln58_fu_510_p2),11));

        sext_ln58_fu_574_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(ret_V_reg_858),11));

        sext_ln67_fu_544_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sub_ln67_fu_538_p2),11));

        sext_ln71_1_fu_672_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(gy_1_fu_664_p3),12));

        sext_ln71_fu_646_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(gx_1_fu_638_p3),12));

    shl_ln1_fu_602_p3 <= (window_2_1_V_load_reg_843 & ap_const_lv1_0);
    shl_ln58_1_fu_577_p3 <= (window_1_2_V_reg_853 & ap_const_lv1_0);
    shl_ln67_1_fu_526_p3 <= (window_0_1_V_fu_118 & ap_const_lv1_0);
    shl_ln_fu_488_p3 <= (window_V_1_1_1_fu_122 & ap_const_lv1_0);
    sub_ln58_1_fu_520_p2 <= std_logic_vector(signed(sext_ln58_1_fu_516_p1) - signed(zext_ln58_2_fu_500_p1));
    sub_ln58_fu_510_p2 <= std_logic_vector(unsigned(zext_ln58_4_fu_507_p1) - unsigned(zext_ln58_fu_496_p1));
    sub_ln67_1_fu_554_p2 <= std_logic_vector(unsigned(add_ln67_fu_548_p2) - unsigned(zext_ln58_2_fu_500_p1));
    sub_ln67_2_fu_613_p2 <= std_logic_vector(unsigned(sub_ln67_1_reg_868) - unsigned(zext_ln67_2_fu_609_p1));
    sub_ln67_fu_538_p2 <= std_logic_vector(unsigned(rhs_V_fu_474_p1) - unsigned(zext_ln58_3_fu_504_p1));
    sub_ln71_1_fu_658_p2 <= std_logic_vector(unsigned(ap_const_lv11_0) - unsigned(gy_fu_618_p2));
    sub_ln71_fu_632_p2 <= std_logic_vector(unsigned(ap_const_lv11_0) - unsigned(gx_fu_594_p2));
    tmp_2_fu_364_p4 <= add_ln20_1_fu_333_p2(30 downto 1);
    tmp_3_fu_624_p3 <= gx_fu_594_p2(10 downto 10);
    tmp_4_fu_650_p3 <= gy_fu_618_p2(10 downto 10);
    tmp_5_fu_402_p4 <= select_ln20_fu_343_p3(30 downto 1);
    tmp_data_V_1_fu_703_p3 <= 
        ap_const_lv8_FF when (tmp_data_V_fu_697_p2(0) = '1') else 
        ap_const_lv8_0;
    tmp_data_V_fu_697_p2 <= (icmp_ln74_fu_687_p2 and and_ln48_fu_692_p2);
    tmp_fu_297_p4 <= r_0_reg_244(30 downto 1);
    tmp_last_V_fu_423_p2 <= (select_ln20_1_fu_356_p3 and icmp_ln83_1_fu_418_p2);
    zext_ln20_1_fu_288_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(r_0_reg_244),32));
    zext_ln20_2_fu_380_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln20_fu_343_p3),32));
    zext_ln20_fu_339_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln20_1_fu_333_p2),32));
    zext_ln215_fu_478_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(line_buffer_V_0_q0),9));
    zext_ln24_fu_313_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(c_0_reg_255),32));
    zext_ln39_fu_396_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln20_fu_343_p3),64));
    zext_ln58_1_fu_584_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(shl_ln58_1_fu_577_p3),11));
    zext_ln58_2_fu_500_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(window_V_2_1_1_fu_130),11));
    zext_ln58_3_fu_504_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_data_V_2_reg_808),9));
    zext_ln58_4_fu_507_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_data_V_2_reg_808),10));
    zext_ln58_fu_496_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(shl_ln_fu_488_p3),10));
    zext_ln67_1_fu_599_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(window_0_2_V_reg_848),11));
    zext_ln67_2_fu_609_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(shl_ln1_fu_602_p3),11));
    zext_ln67_fu_534_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(shl_ln67_1_fu_526_p3),11));
end behav;
