// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2019.1
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="sobel_accel,hls_ip_2019_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z010-clg400-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=8.510000,HLS_SYN_LAT=307206,HLS_SYN_TPT=none,HLS_SYN_MEM=2,HLS_SYN_DSP=4,HLS_SYN_FF=1035,HLS_SYN_LUT=1332,HLS_VERSION=2019_1}" *)

module sobel_accel (
        ap_clk,
        ap_rst_n,
        in_stream_TDATA,
        in_stream_TVALID,
        in_stream_TREADY,
        in_stream_TKEEP,
        in_stream_TSTRB,
        in_stream_TUSER,
        in_stream_TLAST,
        in_stream_TID,
        in_stream_TDEST,
        out_stream_TDATA,
        out_stream_TVALID,
        out_stream_TREADY,
        out_stream_TKEEP,
        out_stream_TSTRB,
        out_stream_TUSER,
        out_stream_TLAST,
        out_stream_TID,
        out_stream_TDEST,
        s_axi_AXILiteS_AWVALID,
        s_axi_AXILiteS_AWREADY,
        s_axi_AXILiteS_AWADDR,
        s_axi_AXILiteS_WVALID,
        s_axi_AXILiteS_WREADY,
        s_axi_AXILiteS_WDATA,
        s_axi_AXILiteS_WSTRB,
        s_axi_AXILiteS_ARVALID,
        s_axi_AXILiteS_ARREADY,
        s_axi_AXILiteS_ARADDR,
        s_axi_AXILiteS_RVALID,
        s_axi_AXILiteS_RREADY,
        s_axi_AXILiteS_RDATA,
        s_axi_AXILiteS_RRESP,
        s_axi_AXILiteS_BVALID,
        s_axi_AXILiteS_BREADY,
        s_axi_AXILiteS_BRESP,
        interrupt
);

parameter    ap_ST_fsm_state1 = 4'd1;
parameter    ap_ST_fsm_state2 = 4'd2;
parameter    ap_ST_fsm_pp0_stage0 = 4'd4;
parameter    ap_ST_fsm_state8 = 4'd8;
parameter    C_S_AXI_AXILITES_DATA_WIDTH = 32;
parameter    C_S_AXI_AXILITES_ADDR_WIDTH = 5;
parameter    C_S_AXI_DATA_WIDTH = 32;

parameter C_S_AXI_AXILITES_WSTRB_WIDTH = (32 / 8);
parameter C_S_AXI_WSTRB_WIDTH = (32 / 8);

input   ap_clk;
input   ap_rst_n;
input  [7:0] in_stream_TDATA;
input   in_stream_TVALID;
output   in_stream_TREADY;
input  [0:0] in_stream_TKEEP;
input  [0:0] in_stream_TSTRB;
input  [0:0] in_stream_TUSER;
input  [0:0] in_stream_TLAST;
input  [0:0] in_stream_TID;
input  [0:0] in_stream_TDEST;
output  [7:0] out_stream_TDATA;
output   out_stream_TVALID;
input   out_stream_TREADY;
output  [0:0] out_stream_TKEEP;
output  [0:0] out_stream_TSTRB;
output  [0:0] out_stream_TUSER;
output  [0:0] out_stream_TLAST;
output  [0:0] out_stream_TID;
output  [0:0] out_stream_TDEST;
input   s_axi_AXILiteS_AWVALID;
output   s_axi_AXILiteS_AWREADY;
input  [C_S_AXI_AXILITES_ADDR_WIDTH - 1:0] s_axi_AXILiteS_AWADDR;
input   s_axi_AXILiteS_WVALID;
output   s_axi_AXILiteS_WREADY;
input  [C_S_AXI_AXILITES_DATA_WIDTH - 1:0] s_axi_AXILiteS_WDATA;
input  [C_S_AXI_AXILITES_WSTRB_WIDTH - 1:0] s_axi_AXILiteS_WSTRB;
input   s_axi_AXILiteS_ARVALID;
output   s_axi_AXILiteS_ARREADY;
input  [C_S_AXI_AXILITES_ADDR_WIDTH - 1:0] s_axi_AXILiteS_ARADDR;
output   s_axi_AXILiteS_RVALID;
input   s_axi_AXILiteS_RREADY;
output  [C_S_AXI_AXILITES_DATA_WIDTH - 1:0] s_axi_AXILiteS_RDATA;
output  [1:0] s_axi_AXILiteS_RRESP;
output   s_axi_AXILiteS_BVALID;
input   s_axi_AXILiteS_BREADY;
output  [1:0] s_axi_AXILiteS_BRESP;
output   interrupt;

 reg    ap_rst_n_inv;
wire    ap_start;
reg    ap_done;
reg    ap_idle;
(* fsm_encoding = "none" *) reg   [3:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    ap_ready;
reg   [7:0] in_stream_V_data_V_0_data_out;
wire    in_stream_V_data_V_0_vld_in;
wire    in_stream_V_data_V_0_vld_out;
wire    in_stream_V_data_V_0_ack_in;
reg    in_stream_V_data_V_0_ack_out;
reg   [7:0] in_stream_V_data_V_0_payload_A;
reg   [7:0] in_stream_V_data_V_0_payload_B;
reg    in_stream_V_data_V_0_sel_rd;
reg    in_stream_V_data_V_0_sel_wr;
wire    in_stream_V_data_V_0_sel;
wire    in_stream_V_data_V_0_load_A;
wire    in_stream_V_data_V_0_load_B;
reg   [1:0] in_stream_V_data_V_0_state;
wire    in_stream_V_data_V_0_state_cmp_full;
wire    in_stream_V_dest_V_0_vld_in;
reg    in_stream_V_dest_V_0_ack_out;
reg   [1:0] in_stream_V_dest_V_0_state;
reg   [7:0] out_stream_V_data_V_1_data_out;
reg    out_stream_V_data_V_1_vld_in;
wire    out_stream_V_data_V_1_vld_out;
wire    out_stream_V_data_V_1_ack_in;
wire    out_stream_V_data_V_1_ack_out;
reg   [7:0] out_stream_V_data_V_1_payload_A;
reg   [7:0] out_stream_V_data_V_1_payload_B;
reg    out_stream_V_data_V_1_sel_rd;
reg    out_stream_V_data_V_1_sel_wr;
wire    out_stream_V_data_V_1_sel;
wire    out_stream_V_data_V_1_load_A;
wire    out_stream_V_data_V_1_load_B;
reg   [1:0] out_stream_V_data_V_1_state;
wire    out_stream_V_data_V_1_state_cmp_full;
wire   [0:0] out_stream_V_keep_V_1_data_out;
reg    out_stream_V_keep_V_1_vld_in;
wire    out_stream_V_keep_V_1_vld_out;
wire    out_stream_V_keep_V_1_ack_out;
reg    out_stream_V_keep_V_1_sel_rd;
wire    out_stream_V_keep_V_1_sel;
reg   [1:0] out_stream_V_keep_V_1_state;
wire   [0:0] out_stream_V_strb_V_1_data_out;
reg    out_stream_V_strb_V_1_vld_in;
wire    out_stream_V_strb_V_1_vld_out;
wire    out_stream_V_strb_V_1_ack_out;
reg    out_stream_V_strb_V_1_sel_rd;
wire    out_stream_V_strb_V_1_sel;
reg   [1:0] out_stream_V_strb_V_1_state;
wire   [0:0] out_stream_V_user_V_1_data_out;
reg    out_stream_V_user_V_1_vld_in;
wire    out_stream_V_user_V_1_vld_out;
wire    out_stream_V_user_V_1_ack_out;
reg    out_stream_V_user_V_1_sel_rd;
wire    out_stream_V_user_V_1_sel;
reg   [1:0] out_stream_V_user_V_1_state;
reg   [0:0] out_stream_V_last_V_1_data_out;
reg    out_stream_V_last_V_1_vld_in;
wire    out_stream_V_last_V_1_vld_out;
wire    out_stream_V_last_V_1_ack_in;
wire    out_stream_V_last_V_1_ack_out;
reg   [0:0] out_stream_V_last_V_1_payload_A;
reg   [0:0] out_stream_V_last_V_1_payload_B;
reg    out_stream_V_last_V_1_sel_rd;
reg    out_stream_V_last_V_1_sel_wr;
wire    out_stream_V_last_V_1_sel;
wire    out_stream_V_last_V_1_load_A;
wire    out_stream_V_last_V_1_load_B;
reg   [1:0] out_stream_V_last_V_1_state;
wire    out_stream_V_last_V_1_state_cmp_full;
wire   [0:0] out_stream_V_id_V_1_data_out;
reg    out_stream_V_id_V_1_vld_in;
wire    out_stream_V_id_V_1_vld_out;
wire    out_stream_V_id_V_1_ack_out;
reg    out_stream_V_id_V_1_sel_rd;
wire    out_stream_V_id_V_1_sel;
reg   [1:0] out_stream_V_id_V_1_state;
wire   [0:0] out_stream_V_dest_V_1_data_out;
reg    out_stream_V_dest_V_1_vld_in;
wire    out_stream_V_dest_V_1_vld_out;
wire    out_stream_V_dest_V_1_ack_out;
reg    out_stream_V_dest_V_1_sel_rd;
wire    out_stream_V_dest_V_1_sel;
reg   [1:0] out_stream_V_dest_V_1_state;
wire   [31:0] width;
wire   [31:0] height;
wire   [9:0] line_buffer_V_0_address0;
reg    line_buffer_V_0_ce0;
wire   [7:0] line_buffer_V_0_q0;
reg    line_buffer_V_0_ce1;
reg    line_buffer_V_0_we1;
wire   [9:0] line_buffer_V_1_address0;
reg    line_buffer_V_1_ce0;
wire   [7:0] line_buffer_V_1_q0;
reg    line_buffer_V_1_ce1;
reg    line_buffer_V_1_we1;
reg    in_stream_TDATA_blk_n;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter0;
wire    ap_block_pp0_stage0;
wire   [0:0] icmp_ln20_fu_322_p2;
reg    out_stream_TDATA_blk_n;
reg    ap_enable_reg_pp0_iter3;
reg   [0:0] icmp_ln20_reg_789;
reg   [0:0] icmp_ln20_reg_789_pp0_iter2_reg;
reg    ap_enable_reg_pp0_iter4;
reg   [0:0] icmp_ln20_reg_789_pp0_iter3_reg;
reg   [63:0] indvar_flatten_reg_233;
reg   [30:0] r_0_reg_244;
reg   [30:0] c_0_reg_255;
reg   [31:0] height_read_reg_750;
reg   [31:0] width_read_reg_756;
wire   [31:0] add_ln83_fu_266_p2;
reg   [31:0] add_ln83_reg_763;
wire    ap_CS_fsm_state2;
wire   [31:0] add_ln83_1_fu_271_p2;
reg   [31:0] add_ln83_1_reg_769;
wire   [63:0] bound_fu_282_p2;
reg   [63:0] bound_reg_774;
wire   [0:0] icmp_ln48_fu_307_p2;
reg   [0:0] icmp_ln48_reg_779;
reg    ap_block_state3_pp0_stage0_iter0;
wire    ap_block_state4_pp0_stage0_iter1;
wire    ap_block_state5_pp0_stage0_iter2;
wire    ap_block_state6_pp0_stage0_iter3;
reg    ap_block_state6_io;
wire    ap_block_state7_pp0_stage0_iter4;
reg    ap_block_state7_io;
reg    ap_block_pp0_stage0_11001;
reg   [0:0] icmp_ln48_reg_779_pp0_iter1_reg;
reg   [0:0] icmp_ln48_reg_779_pp0_iter2_reg;
wire   [0:0] icmp_ln24_fu_317_p2;
reg   [0:0] icmp_ln24_reg_784;
reg   [0:0] icmp_ln24_reg_784_pp0_iter1_reg;
reg   [0:0] icmp_ln24_reg_784_pp0_iter2_reg;
reg   [0:0] icmp_ln20_reg_789_pp0_iter1_reg;
wire   [63:0] add_ln20_fu_327_p2;
wire   [0:0] icmp_ln48_1_fu_374_p2;
reg   [0:0] icmp_ln48_1_reg_798;
reg   [0:0] icmp_ln48_1_reg_798_pp0_iter1_reg;
reg   [0:0] icmp_ln48_1_reg_798_pp0_iter2_reg;
wire   [30:0] select_ln20_3_fu_384_p3;
reg   [7:0] tmp_data_V_2_reg_808;
reg   [9:0] line_buffer_V_0_addr_reg_816;
reg   [9:0] line_buffer_V_1_addr_reg_822;
wire   [0:0] icmp_ln48_2_fu_412_p2;
reg   [0:0] icmp_ln48_2_reg_828;
reg   [0:0] icmp_ln48_2_reg_828_pp0_iter1_reg;
reg   [0:0] icmp_ln48_2_reg_828_pp0_iter2_reg;
wire   [0:0] tmp_last_V_fu_423_p2;
reg   [0:0] tmp_last_V_reg_833;
reg   [0:0] tmp_last_V_reg_833_pp0_iter1_reg;
reg   [0:0] tmp_last_V_reg_833_pp0_iter2_reg;
wire   [30:0] c_fu_429_p2;
reg   [7:0] window_2_1_V_load_reg_843;
reg   [7:0] window_0_2_V_reg_848;
reg    ap_enable_reg_pp0_iter1;
reg   [7:0] window_1_2_V_reg_853;
wire   [8:0] ret_V_fu_482_p2;
reg   [8:0] ret_V_reg_858;
wire   [10:0] sub_ln58_1_fu_520_p2;
reg   [10:0] sub_ln58_1_reg_863;
wire   [10:0] sub_ln67_1_fu_554_p2;
reg   [10:0] sub_ln67_1_reg_868;
wire   [11:0] mag_fu_676_p2;
reg   [11:0] mag_reg_873;
wire   [7:0] tmp_data_V_1_fu_703_p3;
reg    ap_block_pp0_stage0_subdone;
reg    ap_enable_reg_pp0_iter2;
reg    ap_condition_pp0_exit_iter1_state4;
wire   [63:0] zext_ln39_fu_396_p1;
reg   [7:0] window_V_0_1_1_fu_114;
reg   [7:0] window_0_1_V_fu_118;
reg   [7:0] window_V_1_1_1_fu_122;
reg   [7:0] window_1_1_V_fu_126;
reg   [7:0] window_V_2_1_1_fu_130;
reg   [7:0] window_2_1_V_fu_134;
reg    ap_block_pp0_stage0_01001;
wire   [31:0] bound_fu_282_p0;
wire   [31:0] bound_fu_282_p1;
wire   [31:0] zext_ln20_1_fu_288_p1;
wire   [29:0] tmp_fu_297_p4;
wire   [31:0] zext_ln24_fu_313_p1;
wire   [30:0] add_ln20_1_fu_333_p2;
wire   [31:0] zext_ln20_fu_339_p1;
wire   [0:0] icmp_ln83_fu_292_p2;
wire   [0:0] icmp_ln83_2_fu_351_p2;
wire   [29:0] tmp_2_fu_364_p4;
wire   [30:0] select_ln20_fu_343_p3;
wire   [29:0] tmp_5_fu_402_p4;
wire   [31:0] zext_ln20_2_fu_380_p1;
wire   [0:0] select_ln20_1_fu_356_p3;
wire   [0:0] icmp_ln83_1_fu_418_p2;
wire   [8:0] zext_ln215_fu_478_p1;
wire   [8:0] rhs_V_fu_474_p1;
wire   [8:0] shl_ln_fu_488_p3;
wire   [9:0] zext_ln58_4_fu_507_p1;
wire   [9:0] zext_ln58_fu_496_p1;
wire   [9:0] sub_ln58_fu_510_p2;
wire  signed [10:0] sext_ln58_1_fu_516_p1;
wire   [10:0] zext_ln58_2_fu_500_p1;
wire   [8:0] shl_ln67_1_fu_526_p3;
wire   [8:0] zext_ln58_3_fu_504_p1;
wire   [8:0] sub_ln67_fu_538_p2;
wire   [10:0] zext_ln67_fu_534_p1;
wire  signed [10:0] sext_ln67_fu_544_p1;
wire   [10:0] add_ln67_fu_548_p2;
wire   [8:0] shl_ln58_1_fu_577_p3;
wire  signed [10:0] sext_ln58_fu_574_p1;
wire   [10:0] zext_ln58_1_fu_584_p1;
wire   [10:0] add_ln58_fu_588_p2;
wire   [8:0] shl_ln1_fu_602_p3;
wire   [10:0] zext_ln67_2_fu_609_p1;
wire   [10:0] zext_ln67_1_fu_599_p1;
wire   [10:0] sub_ln67_2_fu_613_p2;
wire   [10:0] gx_fu_594_p2;
wire   [0:0] tmp_3_fu_624_p3;
wire   [10:0] sub_ln71_fu_632_p2;
wire   [10:0] gx_1_fu_638_p3;
wire   [10:0] gy_fu_618_p2;
wire   [0:0] tmp_4_fu_650_p3;
wire   [10:0] sub_ln71_1_fu_658_p2;
wire   [10:0] gy_1_fu_664_p3;
wire  signed [11:0] sext_ln71_1_fu_672_p1;
wire  signed [11:0] sext_ln71_fu_646_p1;
wire   [0:0] select_ln20_2_fu_682_p3;
wire   [0:0] icmp_ln74_fu_687_p2;
wire   [0:0] and_ln48_fu_692_p2;
wire   [0:0] tmp_data_V_fu_697_p2;
wire    ap_CS_fsm_state8;
reg    ap_block_state8;
reg   [3:0] ap_NS_fsm;
reg    ap_idle_pp0;
wire    ap_enable_pp0;
wire   [63:0] bound_fu_282_p00;
wire   [63:0] bound_fu_282_p10;

// power-on initialization
initial begin
#0 ap_CS_fsm = 4'd1;
#0 in_stream_V_data_V_0_sel_rd = 1'b0;
#0 in_stream_V_data_V_0_sel_wr = 1'b0;
#0 in_stream_V_data_V_0_state = 2'd0;
#0 in_stream_V_dest_V_0_state = 2'd0;
#0 out_stream_V_data_V_1_sel_rd = 1'b0;
#0 out_stream_V_data_V_1_sel_wr = 1'b0;
#0 out_stream_V_data_V_1_state = 2'd0;
#0 out_stream_V_keep_V_1_sel_rd = 1'b0;
#0 out_stream_V_keep_V_1_state = 2'd0;
#0 out_stream_V_strb_V_1_sel_rd = 1'b0;
#0 out_stream_V_strb_V_1_state = 2'd0;
#0 out_stream_V_user_V_1_sel_rd = 1'b0;
#0 out_stream_V_user_V_1_state = 2'd0;
#0 out_stream_V_last_V_1_sel_rd = 1'b0;
#0 out_stream_V_last_V_1_sel_wr = 1'b0;
#0 out_stream_V_last_V_1_state = 2'd0;
#0 out_stream_V_id_V_1_sel_rd = 1'b0;
#0 out_stream_V_id_V_1_state = 2'd0;
#0 out_stream_V_dest_V_1_sel_rd = 1'b0;
#0 out_stream_V_dest_V_1_state = 2'd0;
#0 ap_enable_reg_pp0_iter0 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
end

sobel_accel_line_bkb #(
    .DataWidth( 8 ),
    .AddressRange( 640 ),
    .AddressWidth( 10 ))
line_buffer_V_0_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(line_buffer_V_0_address0),
    .ce0(line_buffer_V_0_ce0),
    .q0(line_buffer_V_0_q0),
    .address1(line_buffer_V_0_addr_reg_816),
    .ce1(line_buffer_V_0_ce1),
    .we1(line_buffer_V_0_we1),
    .d1(line_buffer_V_1_q0)
);

sobel_accel_line_bkb #(
    .DataWidth( 8 ),
    .AddressRange( 640 ),
    .AddressWidth( 10 ))
line_buffer_V_1_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(line_buffer_V_1_address0),
    .ce0(line_buffer_V_1_ce0),
    .q0(line_buffer_V_1_q0),
    .address1(line_buffer_V_1_addr_reg_822),
    .ce1(line_buffer_V_1_ce1),
    .we1(line_buffer_V_1_we1),
    .d1(tmp_data_V_2_reg_808)
);

sobel_accel_AXILiteS_s_axi #(
    .C_S_AXI_ADDR_WIDTH( C_S_AXI_AXILITES_ADDR_WIDTH ),
    .C_S_AXI_DATA_WIDTH( C_S_AXI_AXILITES_DATA_WIDTH ))
sobel_accel_AXILiteS_s_axi_U(
    .AWVALID(s_axi_AXILiteS_AWVALID),
    .AWREADY(s_axi_AXILiteS_AWREADY),
    .AWADDR(s_axi_AXILiteS_AWADDR),
    .WVALID(s_axi_AXILiteS_WVALID),
    .WREADY(s_axi_AXILiteS_WREADY),
    .WDATA(s_axi_AXILiteS_WDATA),
    .WSTRB(s_axi_AXILiteS_WSTRB),
    .ARVALID(s_axi_AXILiteS_ARVALID),
    .ARREADY(s_axi_AXILiteS_ARREADY),
    .ARADDR(s_axi_AXILiteS_ARADDR),
    .RVALID(s_axi_AXILiteS_RVALID),
    .RREADY(s_axi_AXILiteS_RREADY),
    .RDATA(s_axi_AXILiteS_RDATA),
    .RRESP(s_axi_AXILiteS_RRESP),
    .BVALID(s_axi_AXILiteS_BVALID),
    .BREADY(s_axi_AXILiteS_BREADY),
    .BRESP(s_axi_AXILiteS_BRESP),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .ap_start(ap_start),
    .interrupt(interrupt),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_idle(ap_idle),
    .width(width),
    .height(height)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter0 <= 1'b0;
    end else begin
        if (((icmp_ln20_fu_322_p2 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_enable_reg_pp0_iter0 <= 1'b0;
        end else if ((1'b1 == ap_CS_fsm_state2)) begin
            ap_enable_reg_pp0_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            if ((1'b1 == ap_condition_pp0_exit_iter1_state4)) begin
                ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter0;
            end else if ((1'b1 == 1'b1)) begin
                ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end else if ((1'b1 == ap_CS_fsm_state2)) begin
            ap_enable_reg_pp0_iter4 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        in_stream_V_data_V_0_sel_rd <= 1'b0;
    end else begin
        if (((in_stream_V_data_V_0_ack_out == 1'b1) & (in_stream_V_data_V_0_vld_out == 1'b1))) begin
            in_stream_V_data_V_0_sel_rd <= ~in_stream_V_data_V_0_sel_rd;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        in_stream_V_data_V_0_sel_wr <= 1'b0;
    end else begin
        if (((in_stream_V_data_V_0_ack_in == 1'b1) & (in_stream_V_data_V_0_vld_in == 1'b1))) begin
            in_stream_V_data_V_0_sel_wr <= ~in_stream_V_data_V_0_sel_wr;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        in_stream_V_data_V_0_state <= 2'd0;
    end else begin
        if ((((in_stream_V_data_V_0_state == 2'd2) & (in_stream_V_data_V_0_vld_in == 1'b0)) | ((in_stream_V_data_V_0_state == 2'd3) & (in_stream_V_data_V_0_vld_in == 1'b0) & (in_stream_V_data_V_0_ack_out == 1'b1)))) begin
            in_stream_V_data_V_0_state <= 2'd2;
        end else if ((((in_stream_V_data_V_0_state == 2'd1) & (in_stream_V_data_V_0_ack_out == 1'b0)) | ((in_stream_V_data_V_0_state == 2'd3) & (in_stream_V_data_V_0_ack_out == 1'b0) & (in_stream_V_data_V_0_vld_in == 1'b1)))) begin
            in_stream_V_data_V_0_state <= 2'd1;
        end else if (((~((in_stream_V_data_V_0_vld_in == 1'b0) & (in_stream_V_data_V_0_ack_out == 1'b1)) & ~((in_stream_V_data_V_0_ack_out == 1'b0) & (in_stream_V_data_V_0_vld_in == 1'b1)) & (in_stream_V_data_V_0_state == 2'd3)) | ((in_stream_V_data_V_0_state == 2'd1) & (in_stream_V_data_V_0_ack_out == 1'b1)) | ((in_stream_V_data_V_0_state == 2'd2) & (in_stream_V_data_V_0_vld_in == 1'b1)))) begin
            in_stream_V_data_V_0_state <= 2'd3;
        end else begin
            in_stream_V_data_V_0_state <= 2'd2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        in_stream_V_dest_V_0_state <= 2'd0;
    end else begin
        if ((((in_stream_V_dest_V_0_state == 2'd2) & (in_stream_V_dest_V_0_vld_in == 1'b0)) | ((in_stream_V_dest_V_0_state == 2'd3) & (in_stream_V_dest_V_0_vld_in == 1'b0) & (in_stream_V_dest_V_0_ack_out == 1'b1)))) begin
            in_stream_V_dest_V_0_state <= 2'd2;
        end else if ((((in_stream_V_dest_V_0_state == 2'd1) & (in_stream_V_dest_V_0_ack_out == 1'b0)) | ((in_stream_V_dest_V_0_state == 2'd3) & (in_stream_V_dest_V_0_ack_out == 1'b0) & (in_stream_V_dest_V_0_vld_in == 1'b1)))) begin
            in_stream_V_dest_V_0_state <= 2'd1;
        end else if (((~((in_stream_V_dest_V_0_vld_in == 1'b0) & (in_stream_V_dest_V_0_ack_out == 1'b1)) & ~((in_stream_V_dest_V_0_ack_out == 1'b0) & (in_stream_V_dest_V_0_vld_in == 1'b1)) & (in_stream_V_dest_V_0_state == 2'd3)) | ((in_stream_V_dest_V_0_state == 2'd1) & (in_stream_V_dest_V_0_ack_out == 1'b1)) | ((in_stream_V_dest_V_0_state == 2'd2) & (in_stream_V_dest_V_0_vld_in == 1'b1)))) begin
            in_stream_V_dest_V_0_state <= 2'd3;
        end else begin
            in_stream_V_dest_V_0_state <= 2'd2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        out_stream_V_data_V_1_sel_rd <= 1'b0;
    end else begin
        if (((out_stream_V_data_V_1_ack_out == 1'b1) & (out_stream_V_data_V_1_vld_out == 1'b1))) begin
            out_stream_V_data_V_1_sel_rd <= ~out_stream_V_data_V_1_sel_rd;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        out_stream_V_data_V_1_sel_wr <= 1'b0;
    end else begin
        if (((out_stream_V_data_V_1_ack_in == 1'b1) & (out_stream_V_data_V_1_vld_in == 1'b1))) begin
            out_stream_V_data_V_1_sel_wr <= ~out_stream_V_data_V_1_sel_wr;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        out_stream_V_data_V_1_state <= 2'd0;
    end else begin
        if ((((out_stream_V_data_V_1_state == 2'd2) & (out_stream_V_data_V_1_vld_in == 1'b0)) | ((out_stream_V_data_V_1_state == 2'd3) & (out_stream_V_data_V_1_vld_in == 1'b0) & (out_stream_V_data_V_1_ack_out == 1'b1)))) begin
            out_stream_V_data_V_1_state <= 2'd2;
        end else if ((((out_stream_V_data_V_1_state == 2'd1) & (out_stream_TREADY == 1'b0)) | ((out_stream_V_data_V_1_state == 2'd3) & (out_stream_TREADY == 1'b0) & (out_stream_V_data_V_1_vld_in == 1'b1)))) begin
            out_stream_V_data_V_1_state <= 2'd1;
        end else if (((~((out_stream_V_data_V_1_vld_in == 1'b0) & (out_stream_V_data_V_1_ack_out == 1'b1)) & ~((out_stream_TREADY == 1'b0) & (out_stream_V_data_V_1_vld_in == 1'b1)) & (out_stream_V_data_V_1_state == 2'd3)) | ((out_stream_V_data_V_1_state == 2'd1) & (out_stream_V_data_V_1_ack_out == 1'b1)) | ((out_stream_V_data_V_1_state == 2'd2) & (out_stream_V_data_V_1_vld_in == 1'b1)))) begin
            out_stream_V_data_V_1_state <= 2'd3;
        end else begin
            out_stream_V_data_V_1_state <= 2'd2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        out_stream_V_dest_V_1_sel_rd <= 1'b0;
    end else begin
        if (((out_stream_V_dest_V_1_ack_out == 1'b1) & (out_stream_V_dest_V_1_vld_out == 1'b1))) begin
            out_stream_V_dest_V_1_sel_rd <= ~out_stream_V_dest_V_1_sel_rd;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        out_stream_V_dest_V_1_state <= 2'd0;
    end else begin
        if ((((out_stream_V_dest_V_1_state == 2'd2) & (out_stream_V_dest_V_1_vld_in == 1'b0)) | ((out_stream_V_dest_V_1_state == 2'd3) & (out_stream_V_dest_V_1_vld_in == 1'b0) & (out_stream_V_dest_V_1_ack_out == 1'b1)))) begin
            out_stream_V_dest_V_1_state <= 2'd2;
        end else if ((((out_stream_V_dest_V_1_state == 2'd1) & (out_stream_TREADY == 1'b0)) | ((out_stream_V_dest_V_1_state == 2'd3) & (out_stream_TREADY == 1'b0) & (out_stream_V_dest_V_1_vld_in == 1'b1)))) begin
            out_stream_V_dest_V_1_state <= 2'd1;
        end else if (((~((out_stream_V_dest_V_1_vld_in == 1'b0) & (out_stream_V_dest_V_1_ack_out == 1'b1)) & ~((out_stream_TREADY == 1'b0) & (out_stream_V_dest_V_1_vld_in == 1'b1)) & (out_stream_V_dest_V_1_state == 2'd3)) | ((out_stream_V_dest_V_1_state == 2'd1) & (out_stream_V_dest_V_1_ack_out == 1'b1)) | ((out_stream_V_dest_V_1_state == 2'd2) & (out_stream_V_dest_V_1_vld_in == 1'b1)))) begin
            out_stream_V_dest_V_1_state <= 2'd3;
        end else begin
            out_stream_V_dest_V_1_state <= 2'd2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        out_stream_V_id_V_1_sel_rd <= 1'b0;
    end else begin
        if (((out_stream_V_id_V_1_ack_out == 1'b1) & (out_stream_V_id_V_1_vld_out == 1'b1))) begin
            out_stream_V_id_V_1_sel_rd <= ~out_stream_V_id_V_1_sel_rd;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        out_stream_V_id_V_1_state <= 2'd0;
    end else begin
        if ((((out_stream_V_id_V_1_state == 2'd2) & (out_stream_V_id_V_1_vld_in == 1'b0)) | ((out_stream_V_id_V_1_state == 2'd3) & (out_stream_V_id_V_1_vld_in == 1'b0) & (out_stream_V_id_V_1_ack_out == 1'b1)))) begin
            out_stream_V_id_V_1_state <= 2'd2;
        end else if ((((out_stream_V_id_V_1_state == 2'd1) & (out_stream_TREADY == 1'b0)) | ((out_stream_V_id_V_1_state == 2'd3) & (out_stream_TREADY == 1'b0) & (out_stream_V_id_V_1_vld_in == 1'b1)))) begin
            out_stream_V_id_V_1_state <= 2'd1;
        end else if (((~((out_stream_V_id_V_1_vld_in == 1'b0) & (out_stream_V_id_V_1_ack_out == 1'b1)) & ~((out_stream_TREADY == 1'b0) & (out_stream_V_id_V_1_vld_in == 1'b1)) & (out_stream_V_id_V_1_state == 2'd3)) | ((out_stream_V_id_V_1_state == 2'd1) & (out_stream_V_id_V_1_ack_out == 1'b1)) | ((out_stream_V_id_V_1_state == 2'd2) & (out_stream_V_id_V_1_vld_in == 1'b1)))) begin
            out_stream_V_id_V_1_state <= 2'd3;
        end else begin
            out_stream_V_id_V_1_state <= 2'd2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        out_stream_V_keep_V_1_sel_rd <= 1'b0;
    end else begin
        if (((out_stream_V_keep_V_1_ack_out == 1'b1) & (out_stream_V_keep_V_1_vld_out == 1'b1))) begin
            out_stream_V_keep_V_1_sel_rd <= ~out_stream_V_keep_V_1_sel_rd;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        out_stream_V_keep_V_1_state <= 2'd0;
    end else begin
        if ((((out_stream_V_keep_V_1_state == 2'd2) & (out_stream_V_keep_V_1_vld_in == 1'b0)) | ((out_stream_V_keep_V_1_state == 2'd3) & (out_stream_V_keep_V_1_vld_in == 1'b0) & (out_stream_V_keep_V_1_ack_out == 1'b1)))) begin
            out_stream_V_keep_V_1_state <= 2'd2;
        end else if ((((out_stream_V_keep_V_1_state == 2'd1) & (out_stream_TREADY == 1'b0)) | ((out_stream_V_keep_V_1_state == 2'd3) & (out_stream_TREADY == 1'b0) & (out_stream_V_keep_V_1_vld_in == 1'b1)))) begin
            out_stream_V_keep_V_1_state <= 2'd1;
        end else if (((~((out_stream_V_keep_V_1_vld_in == 1'b0) & (out_stream_V_keep_V_1_ack_out == 1'b1)) & ~((out_stream_TREADY == 1'b0) & (out_stream_V_keep_V_1_vld_in == 1'b1)) & (out_stream_V_keep_V_1_state == 2'd3)) | ((out_stream_V_keep_V_1_state == 2'd1) & (out_stream_V_keep_V_1_ack_out == 1'b1)) | ((out_stream_V_keep_V_1_state == 2'd2) & (out_stream_V_keep_V_1_vld_in == 1'b1)))) begin
            out_stream_V_keep_V_1_state <= 2'd3;
        end else begin
            out_stream_V_keep_V_1_state <= 2'd2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        out_stream_V_last_V_1_sel_rd <= 1'b0;
    end else begin
        if (((out_stream_V_last_V_1_ack_out == 1'b1) & (out_stream_V_last_V_1_vld_out == 1'b1))) begin
            out_stream_V_last_V_1_sel_rd <= ~out_stream_V_last_V_1_sel_rd;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        out_stream_V_last_V_1_sel_wr <= 1'b0;
    end else begin
        if (((out_stream_V_last_V_1_ack_in == 1'b1) & (out_stream_V_last_V_1_vld_in == 1'b1))) begin
            out_stream_V_last_V_1_sel_wr <= ~out_stream_V_last_V_1_sel_wr;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        out_stream_V_last_V_1_state <= 2'd0;
    end else begin
        if ((((out_stream_V_last_V_1_state == 2'd2) & (out_stream_V_last_V_1_vld_in == 1'b0)) | ((out_stream_V_last_V_1_state == 2'd3) & (out_stream_V_last_V_1_vld_in == 1'b0) & (out_stream_V_last_V_1_ack_out == 1'b1)))) begin
            out_stream_V_last_V_1_state <= 2'd2;
        end else if ((((out_stream_V_last_V_1_state == 2'd1) & (out_stream_TREADY == 1'b0)) | ((out_stream_V_last_V_1_state == 2'd3) & (out_stream_TREADY == 1'b0) & (out_stream_V_last_V_1_vld_in == 1'b1)))) begin
            out_stream_V_last_V_1_state <= 2'd1;
        end else if (((~((out_stream_V_last_V_1_vld_in == 1'b0) & (out_stream_V_last_V_1_ack_out == 1'b1)) & ~((out_stream_TREADY == 1'b0) & (out_stream_V_last_V_1_vld_in == 1'b1)) & (out_stream_V_last_V_1_state == 2'd3)) | ((out_stream_V_last_V_1_state == 2'd1) & (out_stream_V_last_V_1_ack_out == 1'b1)) | ((out_stream_V_last_V_1_state == 2'd2) & (out_stream_V_last_V_1_vld_in == 1'b1)))) begin
            out_stream_V_last_V_1_state <= 2'd3;
        end else begin
            out_stream_V_last_V_1_state <= 2'd2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        out_stream_V_strb_V_1_sel_rd <= 1'b0;
    end else begin
        if (((out_stream_V_strb_V_1_ack_out == 1'b1) & (out_stream_V_strb_V_1_vld_out == 1'b1))) begin
            out_stream_V_strb_V_1_sel_rd <= ~out_stream_V_strb_V_1_sel_rd;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        out_stream_V_strb_V_1_state <= 2'd0;
    end else begin
        if ((((out_stream_V_strb_V_1_state == 2'd2) & (out_stream_V_strb_V_1_vld_in == 1'b0)) | ((out_stream_V_strb_V_1_state == 2'd3) & (out_stream_V_strb_V_1_vld_in == 1'b0) & (out_stream_V_strb_V_1_ack_out == 1'b1)))) begin
            out_stream_V_strb_V_1_state <= 2'd2;
        end else if ((((out_stream_V_strb_V_1_state == 2'd1) & (out_stream_TREADY == 1'b0)) | ((out_stream_V_strb_V_1_state == 2'd3) & (out_stream_TREADY == 1'b0) & (out_stream_V_strb_V_1_vld_in == 1'b1)))) begin
            out_stream_V_strb_V_1_state <= 2'd1;
        end else if (((~((out_stream_V_strb_V_1_vld_in == 1'b0) & (out_stream_V_strb_V_1_ack_out == 1'b1)) & ~((out_stream_TREADY == 1'b0) & (out_stream_V_strb_V_1_vld_in == 1'b1)) & (out_stream_V_strb_V_1_state == 2'd3)) | ((out_stream_V_strb_V_1_state == 2'd1) & (out_stream_V_strb_V_1_ack_out == 1'b1)) | ((out_stream_V_strb_V_1_state == 2'd2) & (out_stream_V_strb_V_1_vld_in == 1'b1)))) begin
            out_stream_V_strb_V_1_state <= 2'd3;
        end else begin
            out_stream_V_strb_V_1_state <= 2'd2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        out_stream_V_user_V_1_sel_rd <= 1'b0;
    end else begin
        if (((out_stream_V_user_V_1_ack_out == 1'b1) & (out_stream_V_user_V_1_vld_out == 1'b1))) begin
            out_stream_V_user_V_1_sel_rd <= ~out_stream_V_user_V_1_sel_rd;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        out_stream_V_user_V_1_state <= 2'd0;
    end else begin
        if ((((out_stream_V_user_V_1_state == 2'd2) & (out_stream_V_user_V_1_vld_in == 1'b0)) | ((out_stream_V_user_V_1_state == 2'd3) & (out_stream_V_user_V_1_vld_in == 1'b0) & (out_stream_V_user_V_1_ack_out == 1'b1)))) begin
            out_stream_V_user_V_1_state <= 2'd2;
        end else if ((((out_stream_V_user_V_1_state == 2'd1) & (out_stream_TREADY == 1'b0)) | ((out_stream_V_user_V_1_state == 2'd3) & (out_stream_TREADY == 1'b0) & (out_stream_V_user_V_1_vld_in == 1'b1)))) begin
            out_stream_V_user_V_1_state <= 2'd1;
        end else if (((~((out_stream_V_user_V_1_vld_in == 1'b0) & (out_stream_V_user_V_1_ack_out == 1'b1)) & ~((out_stream_TREADY == 1'b0) & (out_stream_V_user_V_1_vld_in == 1'b1)) & (out_stream_V_user_V_1_state == 2'd3)) | ((out_stream_V_user_V_1_state == 2'd1) & (out_stream_V_user_V_1_ack_out == 1'b1)) | ((out_stream_V_user_V_1_state == 2'd2) & (out_stream_V_user_V_1_vld_in == 1'b1)))) begin
            out_stream_V_user_V_1_state <= 2'd3;
        end else begin
            out_stream_V_user_V_1_state <= 2'd2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln20_fu_322_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        c_0_reg_255 <= c_fu_429_p2;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        c_0_reg_255 <= 31'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln20_fu_322_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        indvar_flatten_reg_233 <= add_ln20_fu_327_p2;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        indvar_flatten_reg_233 <= 64'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln20_fu_322_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        r_0_reg_244 <= select_ln20_3_fu_384_p3;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        r_0_reg_244 <= 31'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        add_ln83_1_reg_769 <= add_ln83_1_fu_271_p2;
        add_ln83_reg_763 <= add_ln83_fu_266_p2;
        bound_reg_774 <= bound_fu_282_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        height_read_reg_750 <= height;
        width_read_reg_756 <= width;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        icmp_ln20_reg_789 <= icmp_ln20_fu_322_p2;
        icmp_ln20_reg_789_pp0_iter1_reg <= icmp_ln20_reg_789;
        icmp_ln24_reg_784 <= icmp_ln24_fu_317_p2;
        icmp_ln24_reg_784_pp0_iter1_reg <= icmp_ln24_reg_784;
        icmp_ln48_1_reg_798_pp0_iter1_reg <= icmp_ln48_1_reg_798;
        icmp_ln48_2_reg_828_pp0_iter1_reg <= icmp_ln48_2_reg_828;
        icmp_ln48_reg_779 <= icmp_ln48_fu_307_p2;
        icmp_ln48_reg_779_pp0_iter1_reg <= icmp_ln48_reg_779;
        tmp_last_V_reg_833_pp0_iter1_reg <= tmp_last_V_reg_833;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        icmp_ln20_reg_789_pp0_iter2_reg <= icmp_ln20_reg_789_pp0_iter1_reg;
        icmp_ln20_reg_789_pp0_iter3_reg <= icmp_ln20_reg_789_pp0_iter2_reg;
        icmp_ln24_reg_784_pp0_iter2_reg <= icmp_ln24_reg_784_pp0_iter1_reg;
        icmp_ln48_1_reg_798_pp0_iter2_reg <= icmp_ln48_1_reg_798_pp0_iter1_reg;
        icmp_ln48_2_reg_828_pp0_iter2_reg <= icmp_ln48_2_reg_828_pp0_iter1_reg;
        icmp_ln48_reg_779_pp0_iter2_reg <= icmp_ln48_reg_779_pp0_iter1_reg;
        tmp_last_V_reg_833_pp0_iter2_reg <= tmp_last_V_reg_833_pp0_iter1_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln20_fu_322_p2 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        icmp_ln48_1_reg_798 <= icmp_ln48_1_fu_374_p2;
        icmp_ln48_2_reg_828 <= icmp_ln48_2_fu_412_p2;
        line_buffer_V_0_addr_reg_816 <= zext_ln39_fu_396_p1;
        line_buffer_V_1_addr_reg_822 <= zext_ln39_fu_396_p1;
        tmp_data_V_2_reg_808 <= in_stream_V_data_V_0_data_out;
        tmp_last_V_reg_833 <= tmp_last_V_fu_423_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((in_stream_V_data_V_0_load_A == 1'b1)) begin
        in_stream_V_data_V_0_payload_A <= in_stream_TDATA;
    end
end

always @ (posedge ap_clk) begin
    if ((in_stream_V_data_V_0_load_B == 1'b1)) begin
        in_stream_V_data_V_0_payload_B <= in_stream_TDATA;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln20_reg_789_pp0_iter1_reg == 1'd0))) begin
        mag_reg_873 <= mag_fu_676_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((out_stream_V_data_V_1_load_A == 1'b1)) begin
        out_stream_V_data_V_1_payload_A <= tmp_data_V_1_fu_703_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((out_stream_V_data_V_1_load_B == 1'b1)) begin
        out_stream_V_data_V_1_payload_B <= tmp_data_V_1_fu_703_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((out_stream_V_last_V_1_load_A == 1'b1)) begin
        out_stream_V_last_V_1_payload_A <= tmp_last_V_reg_833_pp0_iter2_reg;
    end
end

always @ (posedge ap_clk) begin
    if ((out_stream_V_last_V_1_load_B == 1'b1)) begin
        out_stream_V_last_V_1_payload_B <= tmp_last_V_reg_833_pp0_iter2_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln20_reg_789 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ret_V_reg_858 <= ret_V_fu_482_p2;
        sub_ln58_1_reg_863 <= sub_ln58_1_fu_520_p2;
        sub_ln67_1_reg_868 <= sub_ln67_1_fu_554_p2;
        window_2_1_V_load_reg_843 <= window_2_1_V_fu_134;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln20_reg_789 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
        window_0_1_V_fu_118 <= line_buffer_V_0_q0;
        window_0_2_V_reg_848 <= line_buffer_V_0_q0;
        window_1_1_V_fu_126 <= line_buffer_V_1_q0;
        window_1_2_V_reg_853 <= line_buffer_V_1_q0;
        window_2_1_V_fu_134 <= tmp_data_V_2_reg_808;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
        window_V_0_1_1_fu_114 <= window_0_1_V_fu_118;
        window_V_1_1_1_fu_122 <= window_1_1_V_fu_126;
        window_V_2_1_1_fu_130 <= window_2_1_V_fu_134;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
        ap_condition_pp0_exit_iter1_state4 = 1'b1;
    end else begin
        ap_condition_pp0_exit_iter1_state4 = 1'b0;
    end
end

always @ (*) begin
    if ((~((out_stream_V_dest_V_1_state == 2'd1) | (out_stream_V_id_V_1_state == 2'd1) | (out_stream_V_last_V_1_state == 2'd1) | (out_stream_V_user_V_1_state == 2'd1) | (out_stream_V_strb_V_1_state == 2'd1) | (out_stream_V_keep_V_1_state == 2'd1) | (out_stream_V_data_V_1_state == 2'd1) | ((out_stream_V_dest_V_1_state == 2'd3) & (out_stream_TREADY == 1'b0)) | ((out_stream_V_id_V_1_state == 2'd3) & (out_stream_TREADY == 1'b0)) | ((out_stream_V_last_V_1_state == 2'd3) & (out_stream_TREADY == 1'b0)) | ((out_stream_V_user_V_1_state == 2'd3) & (out_stream_TREADY == 1'b0)) | ((out_stream_V_strb_V_1_state == 2'd3) & (out_stream_TREADY == 1'b0)) | ((out_stream_V_keep_V_1_state == 2'd3) & (out_stream_TREADY == 1'b0)) | ((out_stream_V_data_V_1_state == 2'd3) & (out_stream_TREADY == 1'b0))) & (1'b1 == ap_CS_fsm_state8))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((out_stream_V_dest_V_1_state == 2'd1) | (out_stream_V_id_V_1_state == 2'd1) | (out_stream_V_last_V_1_state == 2'd1) | (out_stream_V_user_V_1_state == 2'd1) | (out_stream_V_strb_V_1_state == 2'd1) | (out_stream_V_keep_V_1_state == 2'd1) | (out_stream_V_data_V_1_state == 2'd1) | ((out_stream_V_dest_V_1_state == 2'd3) & (out_stream_TREADY == 1'b0)) | ((out_stream_V_id_V_1_state == 2'd3) & (out_stream_TREADY == 1'b0)) | ((out_stream_V_last_V_1_state == 2'd3) & (out_stream_TREADY == 1'b0)) | ((out_stream_V_user_V_1_state == 2'd3) & (out_stream_TREADY == 1'b0)) | ((out_stream_V_strb_V_1_state == 2'd3) & (out_stream_TREADY == 1'b0)) | ((out_stream_V_keep_V_1_state == 2'd3) & (out_stream_TREADY == 1'b0)) | ((out_stream_V_data_V_1_state == 2'd3) & (out_stream_TREADY == 1'b0))) & (1'b1 == ap_CS_fsm_state8))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (icmp_ln20_fu_322_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        in_stream_TDATA_blk_n = in_stream_V_data_V_0_state[1'd0];
    end else begin
        in_stream_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln20_fu_322_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        in_stream_V_data_V_0_ack_out = 1'b1;
    end else begin
        in_stream_V_data_V_0_ack_out = 1'b0;
    end
end

always @ (*) begin
    if ((in_stream_V_data_V_0_sel == 1'b1)) begin
        in_stream_V_data_V_0_data_out = in_stream_V_data_V_0_payload_B;
    end else begin
        in_stream_V_data_V_0_data_out = in_stream_V_data_V_0_payload_A;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln20_fu_322_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        in_stream_V_dest_V_0_ack_out = 1'b1;
    end else begin
        in_stream_V_dest_V_0_ack_out = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        line_buffer_V_0_ce0 = 1'b1;
    end else begin
        line_buffer_V_0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
        line_buffer_V_0_ce1 = 1'b1;
    end else begin
        line_buffer_V_0_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln20_reg_789 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
        line_buffer_V_0_we1 = 1'b1;
    end else begin
        line_buffer_V_0_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        line_buffer_V_1_ce0 = 1'b1;
    end else begin
        line_buffer_V_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
        line_buffer_V_1_ce1 = 1'b1;
    end else begin
        line_buffer_V_1_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln20_reg_789 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
        line_buffer_V_1_we1 = 1'b1;
    end else begin
        line_buffer_V_1_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0) & (icmp_ln20_reg_789_pp0_iter3_reg == 1'd0) & (ap_enable_reg_pp0_iter4 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0) & (icmp_ln20_reg_789_pp0_iter2_reg == 1'd0) & (ap_enable_reg_pp0_iter3 == 1'b1)))) begin
        out_stream_TDATA_blk_n = out_stream_V_data_V_1_state[1'd1];
    end else begin
        out_stream_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((out_stream_V_data_V_1_sel == 1'b1)) begin
        out_stream_V_data_V_1_data_out = out_stream_V_data_V_1_payload_B;
    end else begin
        out_stream_V_data_V_1_data_out = out_stream_V_data_V_1_payload_A;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln20_reg_789_pp0_iter2_reg == 1'd0) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        out_stream_V_data_V_1_vld_in = 1'b1;
    end else begin
        out_stream_V_data_V_1_vld_in = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln20_reg_789_pp0_iter2_reg == 1'd0) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        out_stream_V_dest_V_1_vld_in = 1'b1;
    end else begin
        out_stream_V_dest_V_1_vld_in = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln20_reg_789_pp0_iter2_reg == 1'd0) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        out_stream_V_id_V_1_vld_in = 1'b1;
    end else begin
        out_stream_V_id_V_1_vld_in = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln20_reg_789_pp0_iter2_reg == 1'd0) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        out_stream_V_keep_V_1_vld_in = 1'b1;
    end else begin
        out_stream_V_keep_V_1_vld_in = 1'b0;
    end
end

always @ (*) begin
    if ((out_stream_V_last_V_1_sel == 1'b1)) begin
        out_stream_V_last_V_1_data_out = out_stream_V_last_V_1_payload_B;
    end else begin
        out_stream_V_last_V_1_data_out = out_stream_V_last_V_1_payload_A;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln20_reg_789_pp0_iter2_reg == 1'd0) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        out_stream_V_last_V_1_vld_in = 1'b1;
    end else begin
        out_stream_V_last_V_1_vld_in = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln20_reg_789_pp0_iter2_reg == 1'd0) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        out_stream_V_strb_V_1_vld_in = 1'b1;
    end else begin
        out_stream_V_strb_V_1_vld_in = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln20_reg_789_pp0_iter2_reg == 1'd0) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        out_stream_V_user_V_1_vld_in = 1'b1;
    end else begin
        out_stream_V_user_V_1_vld_in = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        ap_ST_fsm_pp0_stage0 : begin
            if ((~((ap_enable_reg_pp0_iter0 == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (ap_enable_reg_pp0_iter2 == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone)) & ~((ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone)))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if ((((ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone)) | ((ap_enable_reg_pp0_iter0 == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (ap_enable_reg_pp0_iter2 == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone)))) begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_state8 : begin
            if ((~((out_stream_V_dest_V_1_state == 2'd1) | (out_stream_V_id_V_1_state == 2'd1) | (out_stream_V_last_V_1_state == 2'd1) | (out_stream_V_user_V_1_state == 2'd1) | (out_stream_V_strb_V_1_state == 2'd1) | (out_stream_V_keep_V_1_state == 2'd1) | (out_stream_V_data_V_1_state == 2'd1) | ((out_stream_V_dest_V_1_state == 2'd3) & (out_stream_TREADY == 1'b0)) | ((out_stream_V_id_V_1_state == 2'd3) & (out_stream_TREADY == 1'b0)) | ((out_stream_V_last_V_1_state == 2'd3) & (out_stream_TREADY == 1'b0)) | ((out_stream_V_user_V_1_state == 2'd3) & (out_stream_TREADY == 1'b0)) | ((out_stream_V_strb_V_1_state == 2'd3) & (out_stream_TREADY == 1'b0)) | ((out_stream_V_keep_V_1_state == 2'd3) & (out_stream_TREADY == 1'b0)) | ((out_stream_V_data_V_1_state == 2'd3) & (out_stream_TREADY == 1'b0))) & (1'b1 == ap_CS_fsm_state8))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln20_1_fu_333_p2 = (31'd1 + r_0_reg_244);

assign add_ln20_fu_327_p2 = (indvar_flatten_reg_233 + 64'd1);

assign add_ln58_fu_588_p2 = ($signed(sext_ln58_fu_574_p1) + $signed(zext_ln58_1_fu_584_p1));

assign add_ln67_fu_548_p2 = ($signed(zext_ln67_fu_534_p1) + $signed(sext_ln67_fu_544_p1));

assign add_ln83_1_fu_271_p2 = ($signed(width_read_reg_756) + $signed(32'd4294967295));

assign add_ln83_fu_266_p2 = ($signed(height_read_reg_750) + $signed(32'd4294967295));

assign and_ln48_fu_692_p2 = (select_ln20_2_fu_682_p3 & icmp_ln48_2_reg_828_pp0_iter2_reg);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd3];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = ((icmp_ln20_fu_322_p2 == 1'd0) & (in_stream_V_data_V_0_vld_out == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b1));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = (((1'b1 == ap_block_state7_io) & (ap_enable_reg_pp0_iter4 == 1'b1)) | ((1'b1 == ap_block_state6_io) & (ap_enable_reg_pp0_iter3 == 1'b1)) | ((icmp_ln20_fu_322_p2 == 1'd0) & (in_stream_V_data_V_0_vld_out == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b1)));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = (((1'b1 == ap_block_state7_io) & (ap_enable_reg_pp0_iter4 == 1'b1)) | ((1'b1 == ap_block_state6_io) & (ap_enable_reg_pp0_iter3 == 1'b1)) | ((icmp_ln20_fu_322_p2 == 1'd0) & (in_stream_V_data_V_0_vld_out == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b1)));
end

always @ (*) begin
    ap_block_state3_pp0_stage0_iter0 = ((icmp_ln20_fu_322_p2 == 1'd0) & (in_stream_V_data_V_0_vld_out == 1'b0));
end

assign ap_block_state4_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state6_io = ((icmp_ln20_reg_789_pp0_iter2_reg == 1'd0) & (out_stream_V_data_V_1_ack_in == 1'b0));
end

assign ap_block_state6_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state7_io = ((icmp_ln20_reg_789_pp0_iter3_reg == 1'd0) & (out_stream_V_data_V_1_ack_in == 1'b0));
end

assign ap_block_state7_pp0_stage0_iter4 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state8 = ((out_stream_V_dest_V_1_state == 2'd1) | (out_stream_V_id_V_1_state == 2'd1) | (out_stream_V_last_V_1_state == 2'd1) | (out_stream_V_user_V_1_state == 2'd1) | (out_stream_V_strb_V_1_state == 2'd1) | (out_stream_V_keep_V_1_state == 2'd1) | (out_stream_V_data_V_1_state == 2'd1) | ((out_stream_V_dest_V_1_state == 2'd3) & (out_stream_TREADY == 1'b0)) | ((out_stream_V_id_V_1_state == 2'd3) & (out_stream_TREADY == 1'b0)) | ((out_stream_V_last_V_1_state == 2'd3) & (out_stream_TREADY == 1'b0)) | ((out_stream_V_user_V_1_state == 2'd3) & (out_stream_TREADY == 1'b0)) | ((out_stream_V_strb_V_1_state == 2'd3) & (out_stream_TREADY == 1'b0)) | ((out_stream_V_keep_V_1_state == 2'd3) & (out_stream_TREADY == 1'b0)) | ((out_stream_V_data_V_1_state == 2'd3) & (out_stream_TREADY == 1'b0)));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign bound_fu_282_p0 = bound_fu_282_p00;

assign bound_fu_282_p00 = width_read_reg_756;

assign bound_fu_282_p1 = bound_fu_282_p10;

assign bound_fu_282_p10 = height_read_reg_750;

assign bound_fu_282_p2 = (bound_fu_282_p0 * bound_fu_282_p1);

assign c_fu_429_p2 = (31'd1 + select_ln20_fu_343_p3);

assign gx_1_fu_638_p3 = ((tmp_3_fu_624_p3[0:0] === 1'b1) ? sub_ln71_fu_632_p2 : gx_fu_594_p2);

assign gx_fu_594_p2 = (sub_ln58_1_reg_863 + add_ln58_fu_588_p2);

assign gy_1_fu_664_p3 = ((tmp_4_fu_650_p3[0:0] === 1'b1) ? sub_ln71_1_fu_658_p2 : gy_fu_618_p2);

assign gy_fu_618_p2 = (zext_ln67_1_fu_599_p1 + sub_ln67_2_fu_613_p2);

assign icmp_ln20_fu_322_p2 = ((indvar_flatten_reg_233 == bound_reg_774) ? 1'b1 : 1'b0);

assign icmp_ln24_fu_317_p2 = (($signed(zext_ln24_fu_313_p1) < $signed(width_read_reg_756)) ? 1'b1 : 1'b0);

assign icmp_ln48_1_fu_374_p2 = ((tmp_2_fu_364_p4 != 30'd0) ? 1'b1 : 1'b0);

assign icmp_ln48_2_fu_412_p2 = ((tmp_5_fu_402_p4 != 30'd0) ? 1'b1 : 1'b0);

assign icmp_ln48_fu_307_p2 = ((tmp_fu_297_p4 != 30'd0) ? 1'b1 : 1'b0);

assign icmp_ln74_fu_687_p2 = (($signed(mag_reg_873) > $signed(12'd109)) ? 1'b1 : 1'b0);

assign icmp_ln83_1_fu_418_p2 = ((zext_ln20_2_fu_380_p1 == add_ln83_1_reg_769) ? 1'b1 : 1'b0);

assign icmp_ln83_2_fu_351_p2 = ((zext_ln20_fu_339_p1 == add_ln83_reg_763) ? 1'b1 : 1'b0);

assign icmp_ln83_fu_292_p2 = ((zext_ln20_1_fu_288_p1 == add_ln83_reg_763) ? 1'b1 : 1'b0);

assign in_stream_TREADY = in_stream_V_dest_V_0_state[1'd1];

assign in_stream_V_data_V_0_ack_in = in_stream_V_data_V_0_state[1'd1];

assign in_stream_V_data_V_0_load_A = (in_stream_V_data_V_0_state_cmp_full & ~in_stream_V_data_V_0_sel_wr);

assign in_stream_V_data_V_0_load_B = (in_stream_V_data_V_0_state_cmp_full & in_stream_V_data_V_0_sel_wr);

assign in_stream_V_data_V_0_sel = in_stream_V_data_V_0_sel_rd;

assign in_stream_V_data_V_0_state_cmp_full = ((in_stream_V_data_V_0_state != 2'd1) ? 1'b1 : 1'b0);

assign in_stream_V_data_V_0_vld_in = in_stream_TVALID;

assign in_stream_V_data_V_0_vld_out = in_stream_V_data_V_0_state[1'd0];

assign in_stream_V_dest_V_0_vld_in = in_stream_TVALID;

assign line_buffer_V_0_address0 = zext_ln39_fu_396_p1;

assign line_buffer_V_1_address0 = zext_ln39_fu_396_p1;

assign mag_fu_676_p2 = ($signed(sext_ln71_1_fu_672_p1) + $signed(sext_ln71_fu_646_p1));

assign out_stream_TDATA = out_stream_V_data_V_1_data_out;

assign out_stream_TDEST = out_stream_V_dest_V_1_data_out;

assign out_stream_TID = out_stream_V_id_V_1_data_out;

assign out_stream_TKEEP = out_stream_V_keep_V_1_data_out;

assign out_stream_TLAST = out_stream_V_last_V_1_data_out;

assign out_stream_TSTRB = out_stream_V_strb_V_1_data_out;

assign out_stream_TUSER = out_stream_V_user_V_1_data_out;

assign out_stream_TVALID = out_stream_V_dest_V_1_state[1'd0];

assign out_stream_V_data_V_1_ack_in = out_stream_V_data_V_1_state[1'd1];

assign out_stream_V_data_V_1_ack_out = out_stream_TREADY;

assign out_stream_V_data_V_1_load_A = (out_stream_V_data_V_1_state_cmp_full & ~out_stream_V_data_V_1_sel_wr);

assign out_stream_V_data_V_1_load_B = (out_stream_V_data_V_1_state_cmp_full & out_stream_V_data_V_1_sel_wr);

assign out_stream_V_data_V_1_sel = out_stream_V_data_V_1_sel_rd;

assign out_stream_V_data_V_1_state_cmp_full = ((out_stream_V_data_V_1_state != 2'd1) ? 1'b1 : 1'b0);

assign out_stream_V_data_V_1_vld_out = out_stream_V_data_V_1_state[1'd0];

assign out_stream_V_dest_V_1_ack_out = out_stream_TREADY;

assign out_stream_V_dest_V_1_data_out = 1'd0;

assign out_stream_V_dest_V_1_sel = out_stream_V_dest_V_1_sel_rd;

assign out_stream_V_dest_V_1_vld_out = out_stream_V_dest_V_1_state[1'd0];

assign out_stream_V_id_V_1_ack_out = out_stream_TREADY;

assign out_stream_V_id_V_1_data_out = 1'd0;

assign out_stream_V_id_V_1_sel = out_stream_V_id_V_1_sel_rd;

assign out_stream_V_id_V_1_vld_out = out_stream_V_id_V_1_state[1'd0];

assign out_stream_V_keep_V_1_ack_out = out_stream_TREADY;

assign out_stream_V_keep_V_1_data_out = 1'd1;

assign out_stream_V_keep_V_1_sel = out_stream_V_keep_V_1_sel_rd;

assign out_stream_V_keep_V_1_vld_out = out_stream_V_keep_V_1_state[1'd0];

assign out_stream_V_last_V_1_ack_in = out_stream_V_last_V_1_state[1'd1];

assign out_stream_V_last_V_1_ack_out = out_stream_TREADY;

assign out_stream_V_last_V_1_load_A = (out_stream_V_last_V_1_state_cmp_full & ~out_stream_V_last_V_1_sel_wr);

assign out_stream_V_last_V_1_load_B = (out_stream_V_last_V_1_state_cmp_full & out_stream_V_last_V_1_sel_wr);

assign out_stream_V_last_V_1_sel = out_stream_V_last_V_1_sel_rd;

assign out_stream_V_last_V_1_state_cmp_full = ((out_stream_V_last_V_1_state != 2'd1) ? 1'b1 : 1'b0);

assign out_stream_V_last_V_1_vld_out = out_stream_V_last_V_1_state[1'd0];

assign out_stream_V_strb_V_1_ack_out = out_stream_TREADY;

assign out_stream_V_strb_V_1_data_out = 1'd1;

assign out_stream_V_strb_V_1_sel = out_stream_V_strb_V_1_sel_rd;

assign out_stream_V_strb_V_1_vld_out = out_stream_V_strb_V_1_state[1'd0];

assign out_stream_V_user_V_1_ack_out = out_stream_TREADY;

assign out_stream_V_user_V_1_data_out = 1'd0;

assign out_stream_V_user_V_1_sel = out_stream_V_user_V_1_sel_rd;

assign out_stream_V_user_V_1_vld_out = out_stream_V_user_V_1_state[1'd0];

assign ret_V_fu_482_p2 = (zext_ln215_fu_478_p1 - rhs_V_fu_474_p1);

assign rhs_V_fu_474_p1 = window_V_0_1_1_fu_114;

assign select_ln20_1_fu_356_p3 = ((icmp_ln24_fu_317_p2[0:0] === 1'b1) ? icmp_ln83_fu_292_p2 : icmp_ln83_2_fu_351_p2);

assign select_ln20_2_fu_682_p3 = ((icmp_ln24_reg_784_pp0_iter2_reg[0:0] === 1'b1) ? icmp_ln48_reg_779_pp0_iter2_reg : icmp_ln48_1_reg_798_pp0_iter2_reg);

assign select_ln20_3_fu_384_p3 = ((icmp_ln24_fu_317_p2[0:0] === 1'b1) ? r_0_reg_244 : add_ln20_1_fu_333_p2);

assign select_ln20_fu_343_p3 = ((icmp_ln24_fu_317_p2[0:0] === 1'b1) ? c_0_reg_255 : 31'd0);

assign sext_ln58_1_fu_516_p1 = $signed(sub_ln58_fu_510_p2);

assign sext_ln58_fu_574_p1 = $signed(ret_V_reg_858);

assign sext_ln67_fu_544_p1 = $signed(sub_ln67_fu_538_p2);

assign sext_ln71_1_fu_672_p1 = $signed(gy_1_fu_664_p3);

assign sext_ln71_fu_646_p1 = $signed(gx_1_fu_638_p3);

assign shl_ln1_fu_602_p3 = {{window_2_1_V_load_reg_843}, {1'd0}};

assign shl_ln58_1_fu_577_p3 = {{window_1_2_V_reg_853}, {1'd0}};

assign shl_ln67_1_fu_526_p3 = {{window_0_1_V_fu_118}, {1'd0}};

assign shl_ln_fu_488_p3 = {{window_V_1_1_1_fu_122}, {1'd0}};

assign sub_ln58_1_fu_520_p2 = ($signed(sext_ln58_1_fu_516_p1) - $signed(zext_ln58_2_fu_500_p1));

assign sub_ln58_fu_510_p2 = (zext_ln58_4_fu_507_p1 - zext_ln58_fu_496_p1);

assign sub_ln67_1_fu_554_p2 = (add_ln67_fu_548_p2 - zext_ln58_2_fu_500_p1);

assign sub_ln67_2_fu_613_p2 = (sub_ln67_1_reg_868 - zext_ln67_2_fu_609_p1);

assign sub_ln67_fu_538_p2 = (rhs_V_fu_474_p1 - zext_ln58_3_fu_504_p1);

assign sub_ln71_1_fu_658_p2 = (11'd0 - gy_fu_618_p2);

assign sub_ln71_fu_632_p2 = (11'd0 - gx_fu_594_p2);

assign tmp_2_fu_364_p4 = {{add_ln20_1_fu_333_p2[30:1]}};

assign tmp_3_fu_624_p3 = gx_fu_594_p2[32'd10];

assign tmp_4_fu_650_p3 = gy_fu_618_p2[32'd10];

assign tmp_5_fu_402_p4 = {{select_ln20_fu_343_p3[30:1]}};

assign tmp_data_V_1_fu_703_p3 = ((tmp_data_V_fu_697_p2[0:0] === 1'b1) ? 8'd255 : 8'd0);

assign tmp_data_V_fu_697_p2 = (icmp_ln74_fu_687_p2 & and_ln48_fu_692_p2);

assign tmp_fu_297_p4 = {{r_0_reg_244[30:1]}};

assign tmp_last_V_fu_423_p2 = (select_ln20_1_fu_356_p3 & icmp_ln83_1_fu_418_p2);

assign zext_ln20_1_fu_288_p1 = r_0_reg_244;

assign zext_ln20_2_fu_380_p1 = select_ln20_fu_343_p3;

assign zext_ln20_fu_339_p1 = add_ln20_1_fu_333_p2;

assign zext_ln215_fu_478_p1 = line_buffer_V_0_q0;

assign zext_ln24_fu_313_p1 = c_0_reg_255;

assign zext_ln39_fu_396_p1 = select_ln20_fu_343_p3;

assign zext_ln58_1_fu_584_p1 = shl_ln58_1_fu_577_p3;

assign zext_ln58_2_fu_500_p1 = window_V_2_1_1_fu_130;

assign zext_ln58_3_fu_504_p1 = tmp_data_V_2_reg_808;

assign zext_ln58_4_fu_507_p1 = tmp_data_V_2_reg_808;

assign zext_ln58_fu_496_p1 = shl_ln_fu_488_p3;

assign zext_ln67_1_fu_599_p1 = window_0_2_V_reg_848;

assign zext_ln67_2_fu_609_p1 = shl_ln1_fu_602_p3;

assign zext_ln67_fu_534_p1 = shl_ln67_1_fu_526_p3;

endmodule //sobel_accel
